version: '3.9'
services:
  sql-server:
    container_name: webshop-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Strong@Passw0rd
    ports:
      - 1433:1433