// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(WebshopContext))]
    [Migration("20230411122108_MakingNullableFields")]
    partial class MakingNullableFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BasePrice")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SellPrice")
                        .HasColumnType("float");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f9d568e-6d6d-18c0-12cd-65059b564137"),
                            BasePrice = 955.12,
                            Description = "Consequatur in saepe quasi et quis dolore asperiores.\nEarum saepe unde et.\nQuidem soluta commodi beatae repudiandae beatae quo.\nCumque sed aperiam libero.\nPossimus aut aliquam.",
                            Image = "https://picsum.photos/640/480/?image=555",
                            InStock = true,
                            Name = "Tasty Metal Mouse",
                            SellPrice = 39.509999999999998,
                            Sku = "warakyqwmnn"
                        },
                        new
                        {
                            Id = new Guid("2aa78a7d-2ea2-e051-06fb-b8d496db2459"),
                            BasePrice = 823.84000000000003,
                            Description = "Ut doloribus esse autem magni.\nAut eaque et pariatur excepturi enim tempora unde.",
                            Image = "https://picsum.photos/640/480/?image=806",
                            InStock = false,
                            Name = "Fantastic Metal Mouse",
                            SellPrice = 145.27000000000001,
                            Sku = "ftkpvjdu"
                        },
                        new
                        {
                            Id = new Guid("f1e73704-72e2-3144-e603-5e9f005f295c"),
                            BasePrice = 561.90999999999997,
                            Description = "Sequi aut eaque repellat est earum.\nIllum harum et illo delectus ipsa sunt aut dolorum.",
                            Image = "https://picsum.photos/640/480/?image=980",
                            InStock = true,
                            Name = "Awesome Cotton Sausages",
                            SellPrice = 579.38,
                            Sku = "cztnpwswc"
                        },
                        new
                        {
                            Id = new Guid("5413fd3f-3388-6538-c4ca-25b59fec1dd4"),
                            BasePrice = 37.549999999999997,
                            Description = "Iusto aperiam excepturi rerum tenetur similique accusantium est id et.\nSit accusantium sed.",
                            Image = "https://picsum.photos/640/480/?image=176",
                            InStock = true,
                            Name = "Intelligent Cotton Pants",
                            SellPrice = 180.63999999999999,
                            Sku = "iwiuzctrig"
                        },
                        new
                        {
                            Id = new Guid("9d9b0ed9-12c9-3952-ab9f-eb5b424077a4"),
                            BasePrice = 430.24000000000001,
                            Description = "Error eum officiis.\nSint fuga animi porro voluptas quidem saepe nobis.\nDoloribus modi omnis qui quia modi est eum laudantium.\nMinima blanditiis ratione et maiores et.\nEst dignissimos et enim voluptatum ad voluptatem dolorem id et.",
                            Image = "https://picsum.photos/640/480/?image=934",
                            InStock = false,
                            Name = "Gorgeous Plastic Towels",
                            SellPrice = 467.23000000000002,
                            Sku = "utvuatrzp"
                        },
                        new
                        {
                            Id = new Guid("af7abae0-7b55-53bf-60d3-53fdeaf014bf"),
                            BasePrice = 230.11000000000001,
                            Description = "Sunt fugit quis et eveniet aut dolores laborum praesentium.\nIncidunt consequatur quis voluptatum cum repellendus ex et rem non.\nSequi voluptatibus nobis quaerat.\nBlanditiis qui vero ea animi vitae nulla dolore quisquam.\nEt reiciendis laudantium maiores.",
                            Image = "https://picsum.photos/640/480/?image=222",
                            InStock = true,
                            Name = "Ergonomic Metal Pizza",
                            SellPrice = 546.23000000000002,
                            Sku = "xtrkehkougug"
                        },
                        new
                        {
                            Id = new Guid("fcb4c840-4a5a-1303-dab6-f00ace1e0ff7"),
                            BasePrice = 405.80000000000001,
                            Description = "Quo atque beatae sit molestias.\nVeniam quam corporis quis animi sunt modi.\nVitae minima odit earum sit omnis minima alias.",
                            Image = "https://picsum.photos/640/480/?image=461",
                            InStock = true,
                            Name = "Sleek Fresh Mouse",
                            SellPrice = 181.94,
                            Sku = "kusvmbfzv"
                        },
                        new
                        {
                            Id = new Guid("e7fd993a-30c4-c306-6bd1-35478c821ca3"),
                            BasePrice = 115.89,
                            Description = "Sequi possimus ea et qui qui.\nSunt excepturi veritatis explicabo adipisci.\nEst eos possimus libero maxime corrupti illum porro placeat aut.\nEaque reiciendis itaque dolorem quia officia et porro quos.\nMaiores ipsam aut eos.\nSed cupiditate iste ratione.",
                            Image = "https://picsum.photos/640/480/?image=965",
                            InStock = true,
                            Name = "Licensed Rubber Tuna",
                            SellPrice = 906.21000000000004,
                            Sku = "lkzsmuxsbvn"
                        },
                        new
                        {
                            Id = new Guid("42bd727f-7630-f148-d262-65e242d1bf7a"),
                            BasePrice = 44.590000000000003,
                            Description = "Inventore unde voluptates qui.\nEaque aut illum quidem eius repudiandae itaque nam ullam doloremque.",
                            Image = "https://picsum.photos/640/480/?image=943",
                            InStock = false,
                            Name = "Unbranded Soft Pants",
                            SellPrice = 847.0,
                            Sku = "unoxzbpstk"
                        },
                        new
                        {
                            Id = new Guid("00c6fdbc-fa66-fe69-e635-ba81bf143e98"),
                            BasePrice = 204.49000000000001,
                            Description = "Dolor aut dolores quas autem.\nCupiditate ullam vel ipsam.\nVeniam iure aliquam vel.\nNisi accusamus quia.\nTotam veritatis sunt porro.\nDignissimos adipisci quia ducimus totam nihil et distinctio.",
                            Image = "https://picsum.photos/640/480/?image=1001",
                            InStock = false,
                            Name = "Handcrafted Granite Chicken",
                            SellPrice = 748.90999999999997,
                            Sku = "drywvanssbdq"
                        },
                        new
                        {
                            Id = new Guid("be9bb281-5286-7604-1149-06f50d31696a"),
                            BasePrice = 670.59000000000003,
                            Description = "Id quidem esse eveniet adipisci facilis recusandae fuga consectetur dolores.\nVoluptas et saepe earum nihil.\nAspernatur eos aut non dolor.\nSint ut quia voluptas et culpa et numquam.",
                            Image = "https://picsum.photos/640/480/?image=22",
                            InStock = false,
                            Name = "Tasty Frozen Tuna",
                            SellPrice = 682.29999999999995,
                            Sku = "bmkbqldcgmp"
                        },
                        new
                        {
                            Id = new Guid("7fa8f0f1-d908-bfa9-05ec-06fbca0150aa"),
                            BasePrice = 742.46000000000004,
                            Description = "Harum labore consequatur assumenda qui alias.\nIste voluptas officiis id explicabo.\nDolorem quia quos assumenda quod dolores est necessitatibus dolore.\nEx corporis voluptas vitae et.",
                            Image = "https://picsum.photos/640/480/?image=828",
                            InStock = true,
                            Name = "Small Cotton Pizza",
                            SellPrice = 211.53,
                            Sku = "anynhtiika"
                        },
                        new
                        {
                            Id = new Guid("b6b0eebf-3895-8921-40f2-5960d88363cc"),
                            BasePrice = 473.07999999999998,
                            Description = "Sed sapiente consequuntur voluptatem esse accusantium ea doloremque accusamus.\nCumque id qui assumenda.\nEnim ex est deserunt voluptatem.",
                            Image = "https://picsum.photos/640/480/?image=251",
                            InStock = true,
                            Name = "Sleek Wooden Fish",
                            SellPrice = 351.69,
                            Sku = "rzualkuufrn"
                        },
                        new
                        {
                            Id = new Guid("84012d81-3e79-4e37-ca36-17e51da2bd40"),
                            BasePrice = 593.15999999999997,
                            Description = "Neque enim placeat repudiandae.\nAut voluptatem earum distinctio ut.\nSuscipit culpa cupiditate et delectus dolores totam deleniti.\nAut error et quas illum commodi rerum.",
                            Image = "https://picsum.photos/640/480/?image=294",
                            InStock = true,
                            Name = "Intelligent Granite Mouse",
                            SellPrice = 146.03999999999999,
                            Sku = "emyjaecnrx"
                        },
                        new
                        {
                            Id = new Guid("f6df6c6d-9cfc-8134-2df7-3c96e04b677b"),
                            BasePrice = 396.56,
                            Description = "Voluptatem non qui quasi ut et deleniti animi magni autem.\nCorrupti fugit autem animi voluptas pariatur et eos.\nFugiat iste omnis eveniet.",
                            Image = "https://picsum.photos/640/480/?image=1010",
                            InStock = false,
                            Name = "Licensed Concrete Bike",
                            SellPrice = 154.56999999999999,
                            Sku = "ilmjiwgbbstm"
                        },
                        new
                        {
                            Id = new Guid("ebbf205c-944c-2196-649f-67056239d8cd"),
                            BasePrice = 361.88999999999999,
                            Description = "Quia a est enim repellat adipisci rerum placeat.\nSit quaerat dolorem ut.\nLaboriosam nostrum placeat aspernatur reprehenderit nostrum dolor labore est.",
                            Image = "https://picsum.photos/640/480/?image=339",
                            InStock = true,
                            Name = "Incredible Fresh Shoes",
                            SellPrice = 679.35000000000002,
                            Sku = "drhoysleih"
                        },
                        new
                        {
                            Id = new Guid("fb96eeb8-35df-af9c-3c65-35b2f73939be"),
                            BasePrice = 940.74000000000001,
                            Description = "Voluptate rem nobis et et sit velit velit sunt a.\nSit quam illum quaerat quae sequi modi odit aliquam.\nDelectus eligendi blanditiis.\nRem sed qui repellat sint consequuntur labore voluptates voluptas.\nOptio vel quae voluptas quia.",
                            Image = "https://picsum.photos/640/480/?image=512",
                            InStock = false,
                            Name = "Small Rubber Soap",
                            SellPrice = 754.85000000000002,
                            Sku = "frsmsqdxja"
                        },
                        new
                        {
                            Id = new Guid("3e26dadb-428f-4528-905f-03a7917bcb1e"),
                            BasePrice = 676.83000000000004,
                            Description = "Ut nisi officiis consequatur dolore quia architecto.\nQuis velit porro animi impedit earum dolorem.\nEt et veritatis nobis.\nFacere amet quis voluptatum nemo error nulla est perferendis.\nNon laboriosam earum sunt quia modi maxime occaecati.\nCommodi modi nemo molestiae aut itaque maxime ut quisquam.",
                            Image = "https://picsum.photos/640/480/?image=1065",
                            InStock = true,
                            Name = "Generic Plastic Ball",
                            SellPrice = 954.54999999999995,
                            Sku = "bhwigmdr"
                        },
                        new
                        {
                            Id = new Guid("8771e776-73a1-763b-9bde-5491da7b53ab"),
                            BasePrice = 945.38999999999999,
                            Description = "Sunt a delectus et laudantium deleniti autem sit quo officia.\nOdio aut iste porro atque necessitatibus.\nBlanditiis dolorem soluta maiores explicabo ut occaecati placeat ipsam aliquid.",
                            Image = "https://picsum.photos/640/480/?image=741",
                            InStock = false,
                            Name = "Handcrafted Wooden Chair",
                            SellPrice = 720.28999999999996,
                            Sku = "oxtcvbfvvd"
                        },
                        new
                        {
                            Id = new Guid("3fe40d8a-e59e-c739-ac08-9640a2e43740"),
                            BasePrice = 29.960000000000001,
                            Description = "Ipsam quibusdam repellendus voluptas.\nIpsum molestias blanditiis omnis fuga et voluptatum est nemo dolorem.\nEos provident harum est vel animi laudantium dignissimos a ducimus.",
                            Image = "https://picsum.photos/640/480/?image=1048",
                            InStock = false,
                            Name = "Handmade Rubber Sausages",
                            SellPrice = 847.22000000000003,
                            Sku = "cucfbxklsxsh"
                        },
                        new
                        {
                            Id = new Guid("6e0bf071-d146-0f2d-a800-eec0fe109351"),
                            BasePrice = 245.06,
                            Description = "Qui et tenetur earum accusamus quis rerum.\nCum occaecati facere voluptas.\nSed et dicta necessitatibus consequatur natus iusto facere.",
                            Image = "https://picsum.photos/640/480/?image=562",
                            InStock = true,
                            Name = "Tasty Rubber Tuna",
                            SellPrice = 825.57000000000005,
                            Sku = "jueimlkgznx"
                        },
                        new
                        {
                            Id = new Guid("c5ea8f9b-0b63-2992-3738-7ad105bdf403"),
                            BasePrice = 890.77999999999997,
                            Description = "Enim quos voluptas ut mollitia sed sit dicta mollitia laboriosam.\nEst et in ut ut.\nRepellat quaerat asperiores accusamus consectetur excepturi molestiae porro.",
                            Image = "https://picsum.photos/640/480/?image=654",
                            InStock = false,
                            Name = "Small Wooden Fish",
                            SellPrice = 406.61000000000001,
                            Sku = "smmkcqilrr"
                        },
                        new
                        {
                            Id = new Guid("2fd8670a-5be6-58ac-ef4a-074edd87e8a8"),
                            BasePrice = 189.58000000000001,
                            Description = "Officiis sit temporibus incidunt consequatur neque incidunt eius magni dolores.\nAd voluptas eligendi tempore doloribus aspernatur sint modi distinctio sit.\nAdipisci earum sunt et ex quidem.\nEa eius commodi doloribus nam veritatis recusandae.\nVelit asperiores sit enim dolorem inventore distinctio aut.",
                            Image = "https://picsum.photos/640/480/?image=72",
                            InStock = true,
                            Name = "Tasty Granite Fish",
                            SellPrice = 430.12,
                            Sku = "axtzbtnxndz"
                        },
                        new
                        {
                            Id = new Guid("c53147d8-8bb9-64a0-0cef-0acf0c3f375f"),
                            BasePrice = 520.60000000000002,
                            Description = "Molestias facere ut quaerat voluptatem.\nTempore rerum et vel magnam.",
                            Image = "https://picsum.photos/640/480/?image=1002",
                            InStock = false,
                            Name = "Gorgeous Rubber Bike",
                            SellPrice = 295.16000000000003,
                            Sku = "bfwomeasurbx"
                        },
                        new
                        {
                            Id = new Guid("43a2b9d0-70fc-917f-76d0-c51172875f53"),
                            BasePrice = 390.81,
                            Description = "Officia ut maiores nisi nisi error aperiam ratione corrupti.\nNobis sit quasi voluptas et.\nAutem voluptas minus molestiae consequatur quos voluptatum est.",
                            Image = "https://picsum.photos/640/480/?image=515",
                            InStock = true,
                            Name = "Sleek Wooden Bacon",
                            SellPrice = 92.390000000000001,
                            Sku = "mquastwahvyc"
                        },
                        new
                        {
                            Id = new Guid("f80cced4-ff2b-aff2-34fe-61c1d8082bca"),
                            BasePrice = 339.91000000000003,
                            Description = "Voluptatibus nam facere odio soluta.\nLabore aut quasi odit nihil labore earum sint.\nAtque enim nihil et.\nAut possimus a aspernatur nam omnis modi vitae enim magnam.\nAutem sunt beatae sit reiciendis.\nDolores est nemo ut cupiditate aut omnis odio quod voluptatem.",
                            Image = "https://picsum.photos/640/480/?image=394",
                            InStock = true,
                            Name = "Intelligent Plastic Chips",
                            SellPrice = 269.52999999999997,
                            Sku = "nuqboyvha"
                        },
                        new
                        {
                            Id = new Guid("811f78a2-f095-eb07-ad3f-0665f54b9244"),
                            BasePrice = 761.29999999999995,
                            Description = "Expedita tenetur modi a.\nSimilique nobis ut modi deserunt fugiat.\nVoluptatem ducimus quod quo sunt ut animi error aliquam omnis.\nDistinctio voluptatem nisi enim cupiditate doloremque cumque fugiat optio.\nVoluptatem quam repudiandae repudiandae et dolor dolor non.\nQuis quasi aut.",
                            Image = "https://picsum.photos/640/480/?image=96",
                            InStock = true,
                            Name = "Awesome Soft Shirt",
                            SellPrice = 140.61000000000001,
                            Sku = "ywtxwlmbmich"
                        },
                        new
                        {
                            Id = new Guid("461cd018-4ebb-3a86-df96-74905eef92b5"),
                            BasePrice = 661.19000000000005,
                            Description = "Quasi quasi sed quos sit non praesentium vel esse perferendis.\nVoluptas laboriosam suscipit maxime molestiae.\nEarum omnis eaque laudantium aspernatur.\nDoloremque ut eos aperiam aut recusandae explicabo dicta sit ab.\nEveniet quam nihil aut ut quia molestiae quis.\nOmnis aut porro labore qui voluptate sit.",
                            Image = "https://picsum.photos/640/480/?image=946",
                            InStock = true,
                            Name = "Tasty Concrete Tuna",
                            SellPrice = 292.54000000000002,
                            Sku = "spwoyzmylyw"
                        },
                        new
                        {
                            Id = new Guid("175f177f-fa2b-1569-258e-9f5ab3140fc2"),
                            BasePrice = 753.75999999999999,
                            Description = "A quasi deserunt nulla ut porro animi error aperiam.\nEt nihil beatae doloribus sed sint.",
                            Image = "https://picsum.photos/640/480/?image=422",
                            InStock = false,
                            Name = "Refined Steel Chips",
                            SellPrice = 127.04000000000001,
                            Sku = "lpjhuhnijoda"
                        },
                        new
                        {
                            Id = new Guid("9930b4aa-5cb4-cdc9-bfee-336dfaa22dfe"),
                            BasePrice = 343.11000000000001,
                            Description = "Sapiente aperiam voluptates qui.\nQui iste ab sunt vitae ut odio tenetur.",
                            Image = "https://picsum.photos/640/480/?image=360",
                            InStock = false,
                            Name = "Awesome Steel Ball",
                            SellPrice = 237.94999999999999,
                            Sku = "zxttuoqbgspf"
                        },
                        new
                        {
                            Id = new Guid("bb004292-bb4c-5e30-c1ee-8639965334ba"),
                            BasePrice = 969.94000000000005,
                            Description = "Dolore illo iusto molestiae soluta qui minima.\nPraesentium adipisci qui nulla ab aperiam suscipit voluptatibus officiis placeat.\nTemporibus pariatur neque.",
                            Image = "https://picsum.photos/640/480/?image=70",
                            InStock = false,
                            Name = "Sleek Granite Bacon",
                            SellPrice = 978.75,
                            Sku = "cdjgtdxumdbd"
                        },
                        new
                        {
                            Id = new Guid("0ada1ea0-397c-5eac-8e14-3f8c45a8e73a"),
                            BasePrice = 24.510000000000002,
                            Description = "Dolorem iste maiores adipisci voluptatem.\nRerum molestias esse sit unde voluptas eos assumenda.",
                            Image = "https://picsum.photos/640/480/?image=358",
                            InStock = true,
                            Name = "Practical Plastic Pizza",
                            SellPrice = 295.75,
                            Sku = "duymbefkgl"
                        },
                        new
                        {
                            Id = new Guid("8e35a64b-490e-6651-e31c-f07832f9df46"),
                            BasePrice = 457.89999999999998,
                            Description = "Eveniet eligendi dolorem.\nIn sed dolores minima quibusdam dolorem veritatis vel et.\nNeque laborum neque quas qui sit accusantium deserunt necessitatibus voluptatibus.\nQuam molestiae corrupti vel reiciendis aspernatur nulla odit sapiente.\nOmnis illo molestiae nulla illum possimus quo itaque quia.",
                            Image = "https://picsum.photos/640/480/?image=496",
                            InStock = true,
                            Name = "Generic Rubber Gloves",
                            SellPrice = 381.13999999999999,
                            Sku = "hkhbwlyduc"
                        },
                        new
                        {
                            Id = new Guid("d262db9a-68b3-be27-4c02-2ce7cacc6a72"),
                            BasePrice = 873.27999999999997,
                            Description = "Eos in perspiciatis ut autem aut.\nUllam exercitationem praesentium facere.\nReiciendis asperiores molestiae id in expedita veniam ex laudantium.\nDolor odit dolorum quidem quis assumenda temporibus voluptatibus sit laboriosam.\nSoluta alias sed atque ut.\nFacere sunt ducimus esse maxime mollitia.",
                            Image = "https://picsum.photos/640/480/?image=641",
                            InStock = true,
                            Name = "Unbranded Soft Chicken",
                            SellPrice = 842.0,
                            Sku = "vzauhnzghk"
                        },
                        new
                        {
                            Id = new Guid("4c60222b-d6b3-c348-0af9-4b15fc3ba2ed"),
                            BasePrice = 689.35000000000002,
                            Description = "Reiciendis iste error quia et.\nQuia dolor esse.",
                            Image = "https://picsum.photos/640/480/?image=764",
                            InStock = false,
                            Name = "Sleek Plastic Tuna",
                            SellPrice = 197.66,
                            Sku = "ghlapxppn"
                        },
                        new
                        {
                            Id = new Guid("84c358dc-1c49-3137-b727-52d2309900b4"),
                            BasePrice = 145.91999999999999,
                            Description = "Quasi occaecati minus ut.\nMolestiae odio reiciendis modi ea ut consequuntur.\nEt repudiandae est.\nQui velit impedit ab dolores alias perferendis odit eaque.\nLaborum molestias optio voluptatem iusto necessitatibus id ea eaque odit.\nEum quis dolorum nam omnis cum dicta rerum laborum.",
                            Image = "https://picsum.photos/640/480/?image=252",
                            InStock = false,
                            Name = "Ergonomic Wooden Car",
                            SellPrice = 523.03999999999996,
                            Sku = "tliarrbjep"
                        },
                        new
                        {
                            Id = new Guid("4b13572f-2fa0-ed0e-bd35-b90d1c5f5fd8"),
                            BasePrice = 643.55999999999995,
                            Description = "Nemo voluptates quia quia beatae molestiae nemo reprehenderit nesciunt.\nNemo nam ea iusto minus est et voluptatem.",
                            Image = "https://picsum.photos/640/480/?image=555",
                            InStock = true,
                            Name = "Generic Rubber Chicken",
                            SellPrice = 711.14999999999998,
                            Sku = "kkibazftj"
                        },
                        new
                        {
                            Id = new Guid("cb45ae94-4ab5-9f6b-04e2-ce536e1b0b98"),
                            BasePrice = 511.74000000000001,
                            Description = "Maxime aut doloribus nemo.\nNatus enim omnis est.\nSequi maiores repellat exercitationem eveniet aperiam voluptatem beatae.\nVoluptates omnis ut illum quo aliquid iusto quod voluptate.\nInventore ut non mollitia laudantium rerum.\nSoluta numquam animi vitae excepturi.",
                            Image = "https://picsum.photos/640/480/?image=821",
                            InStock = false,
                            Name = "Refined Steel Shirt",
                            SellPrice = 168.08000000000001,
                            Sku = "uwmfnqpjot"
                        },
                        new
                        {
                            Id = new Guid("2402d8a0-712f-b423-390b-5b5fd2e76aa3"),
                            BasePrice = 41.229999999999997,
                            Description = "Molestias dignissimos ut corporis aut sed non.\nVitae optio non beatae iusto nemo.",
                            Image = "https://picsum.photos/640/480/?image=88",
                            InStock = true,
                            Name = "Handmade Granite Shirt",
                            SellPrice = 14.710000000000001,
                            Sku = "ycmttizqheb"
                        },
                        new
                        {
                            Id = new Guid("5272ed70-891a-0603-e18f-914cc449fdc3"),
                            BasePrice = 28.550000000000001,
                            Description = "Consectetur totam necessitatibus ducimus consequatur nobis fugiat ullam.\nQuia et et rerum a.\nUt ut vero dolor ut harum expedita nesciunt tenetur.\nAt at magni reprehenderit id quia.",
                            Image = "https://picsum.photos/640/480/?image=69",
                            InStock = false,
                            Name = "Ergonomic Frozen Pizza",
                            SellPrice = 616.76999999999998,
                            Sku = "qszseqeamm"
                        },
                        new
                        {
                            Id = new Guid("faeafc14-6702-da14-3024-b00cb39f2d7a"),
                            BasePrice = 259.61000000000001,
                            Description = "Laudantium labore ut eum aspernatur natus autem est asperiores.\nVel facere consequatur.\nOdio quia porro corrupti quaerat quia dolor architecto est.\nCum voluptatum quibusdam autem alias non aut ratione.\nRepudiandae repellendus aut rerum.",
                            Image = "https://picsum.photos/640/480/?image=154",
                            InStock = true,
                            Name = "Handcrafted Granite Salad",
                            SellPrice = 111.54000000000001,
                            Sku = "aqplrpwkvye"
                        },
                        new
                        {
                            Id = new Guid("7829c11a-ef69-ad10-8f23-c5c262ac5082"),
                            BasePrice = 485.05000000000001,
                            Description = "Quo et iste minima quia.\nConsequuntur consectetur dignissimos natus.\nAut corrupti aut veniam aperiam.\nNihil voluptas labore harum.\nLibero non laborum tempore vero rem.",
                            Image = "https://picsum.photos/640/480/?image=540",
                            InStock = false,
                            Name = "Sleek Steel Table",
                            SellPrice = 857.91999999999996,
                            Sku = "gloslyspucri"
                        },
                        new
                        {
                            Id = new Guid("8ef68158-059f-c2ce-d606-1224e88f4bf8"),
                            BasePrice = 948.14999999999998,
                            Description = "Facere non non aperiam qui earum illo sed quidem qui.\nEst quia qui temporibus tempore voluptate facere id incidunt.\nPariatur non sapiente.",
                            Image = "https://picsum.photos/640/480/?image=476",
                            InStock = true,
                            Name = "Awesome Rubber Fish",
                            SellPrice = 832.38999999999999,
                            Sku = "soqnpkjn"
                        },
                        new
                        {
                            Id = new Guid("a730a0e4-fe01-7110-3c33-a33e6b8bdf72"),
                            BasePrice = 205.24000000000001,
                            Description = "Reiciendis aut voluptatibus rerum et.\nCumque accusamus tenetur maiores debitis quasi dolor.\nNumquam veniam accusamus consequuntur qui.\nSapiente iusto occaecati qui eos aut officiis optio.\nIusto aut quia.",
                            Image = "https://picsum.photos/640/480/?image=656",
                            InStock = false,
                            Name = "Gorgeous Cotton Salad",
                            SellPrice = 794.38999999999999,
                            Sku = "ppxrpsff"
                        },
                        new
                        {
                            Id = new Guid("6f93ea62-d64b-7956-bf19-e296846e703d"),
                            BasePrice = 63.609999999999999,
                            Description = "Voluptatum quis quo aliquam omnis earum quam voluptatibus.\nIste placeat quia necessitatibus sint qui voluptates.",
                            Image = "https://picsum.photos/640/480/?image=871",
                            InStock = true,
                            Name = "Licensed Soft Ball",
                            SellPrice = 562.94000000000005,
                            Sku = "jhuxwqwcvve"
                        },
                        new
                        {
                            Id = new Guid("96b81c13-ae6a-fee2-c5ac-55537bcfa721"),
                            BasePrice = 133.03999999999999,
                            Description = "Sit perspiciatis iste et eos incidunt dignissimos veritatis quis consectetur.\nQuidem inventore officiis quae.\nQuod laborum dolor cupiditate non tenetur.\nSunt omnis autem voluptas rerum earum quos est dolorum qui.",
                            Image = "https://picsum.photos/640/480/?image=559",
                            InStock = true,
                            Name = "Awesome Granite Pizza",
                            SellPrice = 37.049999999999997,
                            Sku = "atvdatxdnio"
                        },
                        new
                        {
                            Id = new Guid("3aa14181-ac0d-157d-83f6-a743c25cc8cd"),
                            BasePrice = 843.52999999999997,
                            Description = "Nisi quia rerum ut eius.\nNeque delectus optio corporis ad.\nOptio soluta et veniam et magnam necessitatibus quam non sed.",
                            Image = "https://picsum.photos/640/480/?image=119",
                            InStock = false,
                            Name = "Rustic Cotton Shoes",
                            SellPrice = 626.52999999999997,
                            Sku = "lmxyugxgqfcl"
                        },
                        new
                        {
                            Id = new Guid("1455d3f3-dc3c-a0ad-0389-862293c746b1"),
                            BasePrice = 556.49000000000001,
                            Description = "Eaque error labore fugiat esse nam qui laudantium ut aut.\nDolor nesciunt dolorem quaerat minima sunt inventore voluptatem.\nUt iusto veritatis qui commodi.\nEnim nesciunt quis dolores.\nAutem sit consequatur quos minima voluptatibus aspernatur.\nId quas tempore vel omnis impedit.",
                            Image = "https://picsum.photos/640/480/?image=477",
                            InStock = false,
                            Name = "Sleek Steel Tuna",
                            SellPrice = 773.96000000000004,
                            Sku = "hsvsxcpnaq"
                        },
                        new
                        {
                            Id = new Guid("4968b67a-181f-1085-93d6-4d393f0f1db4"),
                            BasePrice = 809.12,
                            Description = "Consequatur ipsum maiores et quae ex omnis qui aut minima.\nVel quaerat quae numquam delectus mollitia amet sunt.\nHarum voluptas non neque quidem molestias quia eaque dolore modi.\nAccusamus ut ullam molestias.\nOfficia aut et.\nUt quia et.",
                            Image = "https://picsum.photos/640/480/?image=864",
                            InStock = true,
                            Name = "Gorgeous Cotton Ball",
                            SellPrice = 564.32000000000005,
                            Sku = "ueukzhqckp"
                        },
                        new
                        {
                            Id = new Guid("5c734533-e2dd-d944-f5c4-bbd093e0ccb0"),
                            BasePrice = 816.03999999999996,
                            Description = "Libero modi maiores optio et.\nSoluta rerum et voluptatem harum ducimus quasi voluptas sequi.\nEt labore culpa perspiciatis et.",
                            Image = "https://picsum.photos/640/480/?image=1018",
                            InStock = true,
                            Name = "Sleek Rubber Fish",
                            SellPrice = 73.260000000000005,
                            Sku = "wdzewfcs"
                        },
                        new
                        {
                            Id = new Guid("d1100f08-99a0-d0bc-c292-6e63a94cbedb"),
                            BasePrice = 478.41000000000003,
                            Description = "Eius accusamus ullam fugit laboriosam iste sint qui dolor.\nQui recusandae sed.\nVoluptatibus ut quos velit.\nDeleniti harum minus dolor ut temporibus perspiciatis.\nMollitia omnis est quibusdam cupiditate in adipisci nihil est.\nCum atque ea illo ipsa facilis.",
                            Image = "https://picsum.photos/640/480/?image=109",
                            InStock = true,
                            Name = "Incredible Granite Bacon",
                            SellPrice = 60.090000000000003,
                            Sku = "tqfczrki"
                        },
                        new
                        {
                            Id = new Guid("8b84fd55-437f-e4df-7fc2-74e818943599"),
                            BasePrice = 693.65999999999997,
                            Description = "Dolorem voluptatum vero officia.\nVoluptate laboriosam labore quia eos quis.\nAliquam ut ab.\nQuo vel quibusdam.\nEius ullam architecto ut dolor beatae ut.",
                            Image = "https://picsum.photos/640/480/?image=692",
                            InStock = false,
                            Name = "Incredible Granite Chicken",
                            SellPrice = 603.30999999999995,
                            Sku = "dileiggqril"
                        },
                        new
                        {
                            Id = new Guid("82509e4e-0071-db47-d60a-91fb42a9f079"),
                            BasePrice = 675.70000000000005,
                            Description = "Ratione et veniam officiis perferendis.\nDoloribus porro ut omnis dolor.\nUt ut explicabo asperiores.\nTotam modi recusandae magnam maiores quis praesentium voluptatem et.",
                            Image = "https://picsum.photos/640/480/?image=68",
                            InStock = true,
                            Name = "Tasty Concrete Shoes",
                            SellPrice = 68.099999999999994,
                            Sku = "gjkoqrakl"
                        },
                        new
                        {
                            Id = new Guid("9bb84721-93ca-33b1-3801-13b1ab1b59e0"),
                            BasePrice = 386.5,
                            Description = "Ex possimus et doloremque tempore modi.\nDolor est quo consequuntur in molestias veniam.\nVoluptas repudiandae cum quibusdam dolor veniam.\nRepudiandae et itaque et vel in.\nEsse sint molestias et itaque.\nEt reiciendis non ea vel quae quod vel.",
                            Image = "https://picsum.photos/640/480/?image=47",
                            InStock = true,
                            Name = "Small Cotton Chair",
                            SellPrice = 352.81,
                            Sku = "ubkcqxjnr"
                        },
                        new
                        {
                            Id = new Guid("332babd3-6692-b1ab-fd47-e80de252a913"),
                            BasePrice = 856.20000000000005,
                            Description = "Reiciendis facere sint voluptatem sit non ex.\nDolorem voluptas alias ut repudiandae est aut.\nOmnis ea neque.\nAt sed facilis et voluptatibus omnis sunt aut aut sed.\nQuo architecto quam rerum assumenda blanditiis et tenetur.",
                            Image = "https://picsum.photos/640/480/?image=439",
                            InStock = false,
                            Name = "Small Metal Bike",
                            SellPrice = 351.00999999999999,
                            Sku = "ghnlhmdt"
                        },
                        new
                        {
                            Id = new Guid("82250133-526d-57c8-cc18-3412aded6d39"),
                            BasePrice = 374.35000000000002,
                            Description = "Maiores recusandae inventore ut ab sequi ipsam.\nQui nam et.\nCupiditate autem praesentium vel facere est repellendus.\nEligendi quia et culpa et blanditiis sit ut.\nSunt expedita omnis blanditiis.",
                            Image = "https://picsum.photos/640/480/?image=29",
                            InStock = true,
                            Name = "Practical Wooden Salad",
                            SellPrice = 990.77999999999997,
                            Sku = "ohdginivaaon"
                        },
                        new
                        {
                            Id = new Guid("24de1900-f484-4b45-dbb2-c57d7f193712"),
                            BasePrice = 865.99000000000001,
                            Description = "Est pariatur sint.\nVoluptas voluptas omnis atque molestiae culpa.\nIn tempore ut architecto corrupti.",
                            Image = "https://picsum.photos/640/480/?image=885",
                            InStock = false,
                            Name = "Handcrafted Soft Pizza",
                            SellPrice = 87.900000000000006,
                            Sku = "yaokqker"
                        },
                        new
                        {
                            Id = new Guid("46c5bedd-ed4d-dfd3-8ac7-429a425c853a"),
                            BasePrice = 612.28999999999996,
                            Description = "Veritatis impedit repellat.\nExercitationem nobis nihil maiores voluptas.\nEt eius placeat reprehenderit temporibus dicta at.\nCulpa minus asperiores assumenda blanditiis perspiciatis molestias.\nQui natus quis eos repudiandae eius ab modi odio.\nRecusandae eum facere enim quas consequatur ut repellendus nesciunt.",
                            Image = "https://picsum.photos/640/480/?image=155",
                            InStock = false,
                            Name = "Intelligent Plastic Chair",
                            SellPrice = 917.63999999999999,
                            Sku = "pjvizniixdsb"
                        },
                        new
                        {
                            Id = new Guid("8da682ec-047a-bf03-1e90-6159609044d4"),
                            BasePrice = 302.48000000000002,
                            Description = "Rerum eaque odit sed voluptas nostrum qui velit quia laudantium.\nConsectetur voluptates deserunt quia ullam animi.\nNumquam expedita ut.\nRepellendus aut qui et quas facilis veritatis dignissimos.",
                            Image = "https://picsum.photos/640/480/?image=931",
                            InStock = true,
                            Name = "Handcrafted Rubber Pizza",
                            SellPrice = 428.95999999999998,
                            Sku = "wjesfstrk"
                        },
                        new
                        {
                            Id = new Guid("5704c265-68d7-817f-2332-50b008c9f3bc"),
                            BasePrice = 166.41999999999999,
                            Description = "Laudantium ut eius deleniti eius id eum optio nesciunt.\nAut facilis maiores.\nEius quia quo reiciendis.\nVelit sint repudiandae.\nNobis neque officia ad facilis.\nVeniam voluptates voluptatem eum laboriosam.",
                            Image = "https://picsum.photos/640/480/?image=143",
                            InStock = true,
                            Name = "Practical Steel Soap",
                            SellPrice = 734.00999999999999,
                            Sku = "rqyznnlvwpv"
                        },
                        new
                        {
                            Id = new Guid("28cbeace-280d-52d0-b08b-c6d612e0c2ca"),
                            BasePrice = 184.08000000000001,
                            Description = "Laborum neque nostrum corporis et necessitatibus incidunt ut.\nCupiditate ea minus maiores ut ratione est voluptatem et blanditiis.\nSed aut quos provident at.",
                            Image = "https://picsum.photos/640/480/?image=533",
                            InStock = false,
                            Name = "Licensed Steel Hat",
                            SellPrice = 200.24000000000001,
                            Sku = "kkhatfvxf"
                        },
                        new
                        {
                            Id = new Guid("c73f7c88-20ac-3363-922e-667dc75af666"),
                            BasePrice = 459.11000000000001,
                            Description = "Voluptas ipsum ratione.\nSed autem quia quia id accusantium quis.\nMagni incidunt minus.\nEt quia quia molestiae magnam recusandae libero.\nIure nulla id eius voluptas ipsam quisquam voluptatem libero molestias.",
                            Image = "https://picsum.photos/640/480/?image=560",
                            InStock = false,
                            Name = "Handcrafted Frozen Tuna",
                            SellPrice = 36.409999999999997,
                            Sku = "vpywibvcnkgz"
                        },
                        new
                        {
                            Id = new Guid("ad613262-57dc-475d-b353-05776656eece"),
                            BasePrice = 741.55999999999995,
                            Description = "Quia nobis asperiores officiis accusantium repellat vel ut quam.\nDignissimos eligendi consectetur.\nNon beatae sequi eum.\nMolestias praesentium pariatur voluptate et.",
                            Image = "https://picsum.photos/640/480/?image=1031",
                            InStock = true,
                            Name = "Rustic Fresh Bike",
                            SellPrice = 234.53,
                            Sku = "mkhbwgyv"
                        },
                        new
                        {
                            Id = new Guid("51cf19f4-c156-3e9d-b5a4-531f732a0b1f"),
                            BasePrice = 752.74000000000001,
                            Description = "Quidem explicabo commodi tempora.\nIste quis molestiae aut mollitia reiciendis in occaecati.",
                            Image = "https://picsum.photos/640/480/?image=503",
                            InStock = true,
                            Name = "Fantastic Granite Ball",
                            SellPrice = 179.65000000000001,
                            Sku = "tkmeqjzcs"
                        },
                        new
                        {
                            Id = new Guid("b346d458-135a-1c7a-171c-b5a04d9f034e"),
                            BasePrice = 20.870000000000001,
                            Description = "Est perspiciatis sit odio doloremque ea eius ut consequatur rerum.\nA voluptatem fugiat sequi ut vel quisquam provident quos.\nQuibusdam quasi qui dolores amet quisquam.\nMolestias fugiat sit qui consequatur impedit est repellendus cupiditate vel.\nUt expedita et libero dicta est est ipsam.\nDignissimos tenetur suscipit rerum quia deleniti nostrum dolorem voluptas sunt.",
                            Image = "https://picsum.photos/640/480/?image=426",
                            InStock = true,
                            Name = "Unbranded Fresh Ball",
                            SellPrice = 620.80999999999995,
                            Sku = "zwikizcgoz"
                        },
                        new
                        {
                            Id = new Guid("004ba63c-0a4e-c676-88fa-acb6d09738c3"),
                            BasePrice = 737.09000000000003,
                            Description = "Velit voluptas reiciendis qui facere nostrum sint molestiae consectetur.\nRatione debitis doloremque vel.\nAspernatur qui enim voluptatem iure voluptatibus numquam ipsam quis.\nLaudantium at illum tempora.",
                            Image = "https://picsum.photos/640/480/?image=936",
                            InStock = false,
                            Name = "Small Rubber Cheese",
                            SellPrice = 887.65999999999997,
                            Sku = "xnbzsyhjglz"
                        },
                        new
                        {
                            Id = new Guid("292372bb-5a4e-6eb9-2b08-d4fe17337648"),
                            BasePrice = 594.87,
                            Description = "Aut suscipit quae molestiae.\nOdio sed aliquid rerum error est voluptatum deserunt eos.\nEveniet dolorem sit.\nNemo asperiores perspiciatis temporibus reprehenderit omnis maiores accusantium.\nOmnis et labore.",
                            Image = "https://picsum.photos/640/480/?image=648",
                            InStock = true,
                            Name = "Practical Concrete Chips",
                            SellPrice = 868.77999999999997,
                            Sku = "xtulanjmvghz"
                        },
                        new
                        {
                            Id = new Guid("cbca961c-9989-32a1-451d-58d8674bf50d"),
                            BasePrice = 825.44000000000005,
                            Description = "Omnis error itaque cum unde et culpa sed.\nLaborum adipisci et animi placeat soluta.\nAd repellendus vel dolorum ut.\nIpsa perspiciatis atque deleniti numquam facilis et consequatur.\nCorrupti facilis ea laboriosam tenetur provident qui quae voluptas ea.\nNon rem et.",
                            Image = "https://picsum.photos/640/480/?image=344",
                            InStock = true,
                            Name = "Practical Plastic Ball",
                            SellPrice = 616.21000000000004,
                            Sku = "bazezmgyqdq"
                        },
                        new
                        {
                            Id = new Guid("cd19fb5a-53b4-6097-4b3b-ef105d652732"),
                            BasePrice = 304.10000000000002,
                            Description = "Ut voluptas voluptas voluptatibus explicabo commodi.\nVoluptas consequuntur aut magnam praesentium.\nCum voluptatibus cupiditate voluptas id corrupti voluptatem qui iure.\nNecessitatibus voluptate aut sed incidunt suscipit.\nEos atque ab voluptatem in enim eius odit quia.\nNesciunt doloribus sequi illum deleniti ut sequi molestias dicta.",
                            Image = "https://picsum.photos/640/480/?image=1041",
                            InStock = false,
                            Name = "Refined Soft Chicken",
                            SellPrice = 983.52999999999997,
                            Sku = "avymakaufj"
                        },
                        new
                        {
                            Id = new Guid("51a2e216-9526-e496-1ce4-84b1d524376f"),
                            BasePrice = 17.690000000000001,
                            Description = "Dolor velit vero vero saepe non consequatur aliquam maxime.\nEst est tenetur ut omnis esse blanditiis libero corporis.\nQuidem mollitia facilis corporis modi harum voluptas.\nMagnam similique quisquam adipisci dolores modi vel delectus aut nihil.",
                            Image = "https://picsum.photos/640/480/?image=189",
                            InStock = true,
                            Name = "Ergonomic Wooden Bacon",
                            SellPrice = 626.97000000000003,
                            Sku = "wmgssrdnaaj"
                        },
                        new
                        {
                            Id = new Guid("fc7698f4-095d-09b7-4e64-3503af281bbf"),
                            BasePrice = 263.25999999999999,
                            Description = "Voluptas repudiandae quod in aut accusamus minus non ipsa.\nAliquid explicabo vel est repudiandae dolores.\nAut aut ipsa occaecati possimus deleniti dolor.\nCorporis tempora accusantium.\nNon alias rerum voluptas sit ut dolores excepturi labore voluptas.\nEnim ipsa earum.",
                            Image = "https://picsum.photos/640/480/?image=266",
                            InStock = false,
                            Name = "Fantastic Frozen Sausages",
                            SellPrice = 215.71000000000001,
                            Sku = "tszramizyibp"
                        },
                        new
                        {
                            Id = new Guid("b977177d-bf81-0451-01ce-f0a9022f29b7"),
                            BasePrice = 811.61000000000001,
                            Description = "Fuga dolore voluptate nostrum sit et.\nAperiam culpa incidunt sed accusamus molestiae sit labore.\nTenetur fugiat dolores dignissimos ducimus velit necessitatibus id.",
                            Image = "https://picsum.photos/640/480/?image=549",
                            InStock = true,
                            Name = "Rustic Plastic Gloves",
                            SellPrice = 869.50999999999999,
                            Sku = "lafxrvsbhas"
                        },
                        new
                        {
                            Id = new Guid("b392eec2-b82c-f7e4-b113-d9e2774d7da1"),
                            BasePrice = 561.69000000000005,
                            Description = "Cupiditate velit accusamus sit aut quam.\nAut qui voluptatum.\nVitae reprehenderit dignissimos eum sit suscipit labore neque nobis.\nEt quae nesciunt adipisci nostrum et corporis rerum id autem.\nQuia officia ut non voluptas dolor.",
                            Image = "https://picsum.photos/640/480/?image=332",
                            InStock = false,
                            Name = "Generic Fresh Shirt",
                            SellPrice = 91.840000000000003,
                            Sku = "hsxnafiphxmz"
                        },
                        new
                        {
                            Id = new Guid("76e80e97-6692-1399-72ca-33ebaff22f91"),
                            BasePrice = 861.67999999999995,
                            Description = "Modi aperiam accusamus debitis.\nEt nihil reiciendis numquam.",
                            Image = "https://picsum.photos/640/480/?image=875",
                            InStock = true,
                            Name = "Ergonomic Wooden Fish",
                            SellPrice = 468.50999999999999,
                            Sku = "bxggwhge"
                        },
                        new
                        {
                            Id = new Guid("da3dbf82-53b9-5e29-3118-342626f9a75b"),
                            BasePrice = 792.88,
                            Description = "Sunt qui voluptatem perferendis quidem.\nEst esse soluta veniam ipsa ullam aliquid.\nVoluptate ut illo velit eum.\nEaque quia et.\nPraesentium debitis fugiat dolore placeat corporis.",
                            Image = "https://picsum.photos/640/480/?image=114",
                            InStock = true,
                            Name = "Intelligent Wooden Cheese",
                            SellPrice = 239.59,
                            Sku = "nsqwnuryvmvv"
                        },
                        new
                        {
                            Id = new Guid("83648d9d-cc0b-bf20-3d29-981b3764d314"),
                            BasePrice = 839.38999999999999,
                            Description = "Iure excepturi autem accusantium quae id est tempore.\nEligendi laudantium ratione soluta harum alias atque.\nError enim reiciendis cupiditate quibusdam ut debitis.\nQuo qui voluptate et cumque quo nesciunt.\nQuia non sed ut non.\nMolestias et non harum.",
                            Image = "https://picsum.photos/640/480/?image=943",
                            InStock = true,
                            Name = "Intelligent Cotton Pants",
                            SellPrice = 499.23000000000002,
                            Sku = "chknbyczay"
                        },
                        new
                        {
                            Id = new Guid("e7329b52-1c73-8bec-731d-52dbf68ca36c"),
                            BasePrice = 741.66999999999996,
                            Description = "Vitae molestiae in maxime impedit sequi voluptas.\nMaiores sint ut qui nulla.\nNam iste ut iste facilis qui soluta sit est.",
                            Image = "https://picsum.photos/640/480/?image=738",
                            InStock = false,
                            Name = "Licensed Steel Bacon",
                            SellPrice = 643.82000000000005,
                            Sku = "caoyericj"
                        },
                        new
                        {
                            Id = new Guid("e5bc904e-6499-4b31-2d45-2a6332680537"),
                            BasePrice = 496.44,
                            Description = "Itaque nemo odio et distinctio est dolorem minima occaecati.\nIpsam quo repellendus facilis.",
                            Image = "https://picsum.photos/640/480/?image=1025",
                            InStock = true,
                            Name = "Fantastic Frozen Shirt",
                            SellPrice = 905.17999999999995,
                            Sku = "yzqmqzqix"
                        },
                        new
                        {
                            Id = new Guid("a0ea37a5-ad75-c4b9-52d2-88332a6d56d7"),
                            BasePrice = 986.92999999999995,
                            Description = "Earum voluptatum natus vero ut sapiente cumque consequuntur vel totam.\nQuis eaque ut maiores.",
                            Image = "https://picsum.photos/640/480/?image=818",
                            InStock = true,
                            Name = "Practical Frozen Chair",
                            SellPrice = 302.49000000000001,
                            Sku = "opofgnxoyv"
                        },
                        new
                        {
                            Id = new Guid("e00af00f-83e1-4b99-f008-71cfd9a037df"),
                            BasePrice = 466.56999999999999,
                            Description = "Aliquid placeat error est totam explicabo quia distinctio.\nMinima eum aspernatur assumenda et est est corporis possimus.",
                            Image = "https://picsum.photos/640/480/?image=376",
                            InStock = true,
                            Name = "Small Wooden Shirt",
                            SellPrice = 213.96000000000001,
                            Sku = "rvhmxeyi"
                        },
                        new
                        {
                            Id = new Guid("ed55b290-5d4a-db71-0d2d-3f372c3daad5"),
                            BasePrice = 135.11000000000001,
                            Description = "Eligendi ut enim sed fugiat.\nIusto quo fugit id aliquam quo impedit aspernatur.",
                            Image = "https://picsum.photos/640/480/?image=289",
                            InStock = true,
                            Name = "Licensed Cotton Fish",
                            SellPrice = 249.47,
                            Sku = "evtddxjvnr"
                        },
                        new
                        {
                            Id = new Guid("b0f47665-1ac0-d48c-ddc0-7a57b9ca7887"),
                            BasePrice = 56.039999999999999,
                            Description = "Aut saepe iure accusantium et soluta nulla eos modi quia.\nUt totam neque doloribus placeat officiis voluptates delectus pariatur ea.\nSapiente pariatur saepe.\nQuam quos eveniet odit rerum sapiente deserunt et aut.\nUt et est.",
                            Image = "https://picsum.photos/640/480/?image=520",
                            InStock = false,
                            Name = "Licensed Soft Bacon",
                            SellPrice = 299.85000000000002,
                            Sku = "cxzztgfp"
                        },
                        new
                        {
                            Id = new Guid("c5fe883d-7d00-611a-b7a2-5c86068d6b40"),
                            BasePrice = 381.99000000000001,
                            Description = "Nostrum id expedita quo error quibusdam tenetur vero omnis asperiores.\nVoluptas sed distinctio enim architecto.\nAut nihil earum repudiandae est.\nNam autem aut voluptatem.\nUt quis temporibus quis blanditiis dolorum excepturi quasi et eum.",
                            Image = "https://picsum.photos/640/480/?image=52",
                            InStock = true,
                            Name = "Refined Fresh Shirt",
                            SellPrice = 560.01999999999998,
                            Sku = "gmbscuppr"
                        },
                        new
                        {
                            Id = new Guid("564541ab-8712-2e70-827c-a10e70db0a99"),
                            BasePrice = 478.30000000000001,
                            Description = "Possimus sint ab.\nAt corporis voluptas fugiat voluptatem totam error.\nVoluptatem explicabo rerum in eveniet explicabo aut qui.",
                            Image = "https://picsum.photos/640/480/?image=95",
                            InStock = false,
                            Name = "Fantastic Fresh Keyboard",
                            SellPrice = 986.47000000000003,
                            Sku = "boeagkfqx"
                        },
                        new
                        {
                            Id = new Guid("b6eccb37-f80e-d9ca-b39a-84680e3b3651"),
                            BasePrice = 621.52999999999997,
                            Description = "Qui sint voluptatem fuga est quos voluptatem amet ducimus molestiae.\nSunt cupiditate autem voluptatum ut ea magni.\nDolorum neque non sequi ex maxime numquam.\nEos inventore a praesentium provident cum unde optio.\nOptio nulla qui incidunt non quia aperiam.\nCumque neque autem provident quia commodi.",
                            Image = "https://picsum.photos/640/480/?image=818",
                            InStock = false,
                            Name = "Handcrafted Metal Pants",
                            SellPrice = 305.55000000000001,
                            Sku = "lxrvwxvkyys"
                        },
                        new
                        {
                            Id = new Guid("59125dc8-0506-9b4e-3368-f2b5461539b4"),
                            BasePrice = 513.38,
                            Description = "Molestias totam provident deserunt earum.\nAtque possimus praesentium sunt.\nAspernatur impedit voluptatem fugit.\nLaudantium ea eligendi ut in voluptas vitae adipisci aut amet.\nSed mollitia suscipit excepturi facilis ratione fugit et cum tempora.\nSit explicabo qui et quod quasi quasi eveniet.",
                            Image = "https://picsum.photos/640/480/?image=633",
                            InStock = false,
                            Name = "Handcrafted Fresh Towels",
                            SellPrice = 712.83000000000004,
                            Sku = "hajesaprtyh"
                        },
                        new
                        {
                            Id = new Guid("2b29144a-89ba-7fad-a53a-8f1cfc37c2dd"),
                            BasePrice = 878.5,
                            Description = "Error est beatae voluptas quia nisi cumque.\nVitae voluptates ut optio et nemo nihil quisquam quibusdam.\nNihil asperiores et consequatur sunt consequuntur ipsam.\nQui qui qui nam laborum omnis eligendi earum.",
                            Image = "https://picsum.photos/640/480/?image=708",
                            InStock = true,
                            Name = "Incredible Soft Shirt",
                            SellPrice = 499.27999999999997,
                            Sku = "mkgrokysui"
                        },
                        new
                        {
                            Id = new Guid("5aa522f6-4a16-34ea-f530-e253985886a1"),
                            BasePrice = 173.03,
                            Description = "Labore est ut modi ratione.\nEt dolore eum totam.\nEt iste accusantium illum architecto.\nItaque recusandae ex non dolorem odit pariatur.",
                            Image = "https://picsum.photos/640/480/?image=290",
                            InStock = true,
                            Name = "Handcrafted Frozen Gloves",
                            SellPrice = 810.11000000000001,
                            Sku = "nsaxmhcgad"
                        },
                        new
                        {
                            Id = new Guid("2933d59b-895d-b08e-3861-cced9e674d1b"),
                            BasePrice = 609.01999999999998,
                            Description = "Sit laborum corporis dolorem.\nOdio laudantium provident aut.\nEos quaerat provident est.\nIncidunt occaecati est natus.\nId magnam minus illum temporibus maiores.",
                            Image = "https://picsum.photos/640/480/?image=160",
                            InStock = true,
                            Name = "Tasty Cotton Hat",
                            SellPrice = 75.299999999999997,
                            Sku = "lxmopcqw"
                        },
                        new
                        {
                            Id = new Guid("ab6a9fe5-c014-e87e-0ecf-e76ae86c52d1"),
                            BasePrice = 693.24000000000001,
                            Description = "Qui sit tenetur atque accusamus voluptas magnam voluptatem amet.\nSit nesciunt aut id omnis atque.",
                            Image = "https://picsum.photos/640/480/?image=6",
                            InStock = false,
                            Name = "Handmade Soft Fish",
                            SellPrice = 297.10000000000002,
                            Sku = "eisezghwnx"
                        },
                        new
                        {
                            Id = new Guid("bfec52a8-33a3-d58a-b569-7fa576dfcca8"),
                            BasePrice = 83.909999999999997,
                            Description = "Officia et iste architecto eos.\nAssumenda aut est et quia molestias.\nEius facere molestias.",
                            Image = "https://picsum.photos/640/480/?image=874",
                            InStock = false,
                            Name = "Awesome Fresh Sausages",
                            SellPrice = 70.269999999999996,
                            Sku = "tayrgczgrd"
                        },
                        new
                        {
                            Id = new Guid("a1e2bbc6-96f1-e5f4-43ce-8741526ac1f8"),
                            BasePrice = 895.26999999999998,
                            Description = "Repellat repudiandae voluptatem quo deserunt rerum ea ut.\nVoluptas sunt facere perferendis quae natus reprehenderit ab ab consequatur.\nCumque quo eligendi culpa omnis dolorem minus qui.\nMinima voluptatem veritatis voluptas alias perferendis placeat.\nEt nulla animi aliquam non eius qui.\nVelit qui quos eveniet dolorem.",
                            Image = "https://picsum.photos/640/480/?image=320",
                            InStock = true,
                            Name = "Refined Steel Pants",
                            SellPrice = 116.02,
                            Sku = "qznrzltdgg"
                        },
                        new
                        {
                            Id = new Guid("e8dde4b7-cb1e-0402-5a58-987192fa70fe"),
                            BasePrice = 196.43000000000001,
                            Description = "Eum ut ea.\nAut earum dolor cupiditate consequatur.\nHic deserunt omnis amet non.\nVeritatis amet earum.",
                            Image = "https://picsum.photos/640/480/?image=468",
                            InStock = false,
                            Name = "Generic Fresh Fish",
                            SellPrice = 228.56999999999999,
                            Sku = "kbgexkog"
                        },
                        new
                        {
                            Id = new Guid("fc7cb712-3628-896e-f256-55fad45b3558"),
                            BasePrice = 922.42999999999995,
                            Description = "Sapiente praesentium debitis odit.\nEveniet similique quas doloremque excepturi non.\nNisi cupiditate et et eum sunt ipsam non.",
                            Image = "https://picsum.photos/640/480/?image=346",
                            InStock = false,
                            Name = "Generic Frozen Hat",
                            SellPrice = 291.35000000000002,
                            Sku = "haniqvjbr"
                        },
                        new
                        {
                            Id = new Guid("6c91b6cb-ad56-e683-3d3e-eae9eaf69ebf"),
                            BasePrice = 150.08000000000001,
                            Description = "Totam saepe dolorem.\nTemporibus odio quae ut aut.\nConsequatur qui enim.",
                            Image = "https://picsum.photos/640/480/?image=385",
                            InStock = false,
                            Name = "Rustic Steel Ball",
                            SellPrice = 793.36000000000001,
                            Sku = "eugmplvib"
                        },
                        new
                        {
                            Id = new Guid("9207f714-3857-0f8f-2e1b-8004f4ea4b36"),
                            BasePrice = 480.49000000000001,
                            Description = "Ratione architecto sint fugit dolores voluptatibus dolorum.\nSed maxime nesciunt iusto ut occaecati et quo unde.\nNon amet quia quos quo.\nEa maxime asperiores a ipsa quod quis et repellat molestias.\nIpsam sequi velit possimus enim.",
                            Image = "https://picsum.photos/640/480/?image=253",
                            InStock = false,
                            Name = "Tasty Metal Soap",
                            SellPrice = 353.66000000000003,
                            Sku = "pymhoymi"
                        },
                        new
                        {
                            Id = new Guid("54050131-cb44-01e2-a5b0-01c2dbb50d07"),
                            BasePrice = 445.02999999999997,
                            Description = "Quia et nisi omnis.\nEt dignissimos at ullam libero accusantium commodi eligendi nulla et.\nDeleniti aut omnis quia molestiae dolores modi soluta.\nNemo enim ipsa architecto natus id alias reprehenderit.",
                            Image = "https://picsum.photos/640/480/?image=1043",
                            InStock = true,
                            Name = "Handmade Wooden Pizza",
                            SellPrice = 75.629999999999995,
                            Sku = "rpbfzvof"
                        },
                        new
                        {
                            Id = new Guid("38451d51-6e2e-293d-f0f7-218b815b1a9d"),
                            BasePrice = 714.45000000000005,
                            Description = "Expedita est veritatis fugit ipsam autem est occaecati ex.\nReprehenderit corrupti ut sapiente laudantium et minus.\nAliquid blanditiis necessitatibus et illum.\nEst ut suscipit in sit dicta sequi rerum praesentium.\nSint deleniti consequuntur voluptatem corporis unde.",
                            Image = "https://picsum.photos/640/480/?image=464",
                            InStock = false,
                            Name = "Unbranded Cotton Pants",
                            SellPrice = 774.79999999999995,
                            Sku = "oxtsjvnwwmtl"
                        },
                        new
                        {
                            Id = new Guid("e66b9610-03c6-f610-5431-b144fad5549a"),
                            BasePrice = 487.67000000000002,
                            Description = "Quia voluptas saepe molestias dicta ducimus voluptatem quasi odit.\nPerspiciatis et numquam odit.\nFugiat quisquam in sit pariatur.\nEaque pariatur non ad fuga officia minima aliquam blanditiis.",
                            Image = "https://picsum.photos/640/480/?image=10",
                            InStock = false,
                            Name = "Refined Fresh Sausages",
                            SellPrice = 503.88999999999999,
                            Sku = "nsfsuamhxm"
                        },
                        new
                        {
                            Id = new Guid("56b9ba20-8b40-0b0f-288d-4c0cd070330b"),
                            BasePrice = 197.87,
                            Description = "Fugiat saepe est provident nemo perferendis ut molestiae sit.\nVoluptas expedita reiciendis autem atque itaque deleniti quo enim commodi.\nA vel et explicabo ratione laborum est voluptas.\nIllum repellendus porro necessitatibus culpa.\nHic alias quibusdam et aut dolores error atque.",
                            Image = "https://picsum.photos/640/480/?image=76",
                            InStock = true,
                            Name = "Small Metal Shirt",
                            SellPrice = 763.58000000000004,
                            Sku = "amdcpgugjl"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
