// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(WebshopContext))]
    [Migration("20230406091104_InitializeDatabase")]
    partial class InitializeDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BasePrice")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SellPrice")
                        .HasColumnType("float");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19eae9e0-bc6d-f539-f965-1055bd0feb08"),
                            BasePrice = 37.189999999999998,
                            Description = "Earum rem accusantium.\nOccaecati et totam.\nEaque harum quo rerum quaerat vitae consequuntur.\nVelit vel omnis eum voluptates at.\nCumque voluptas labore iusto atque quod veritatis.\nEos ut quas facilis harum et explicabo qui et et.",
                            Image = "https://picsum.photos/640/480/?image=958",
                            InStock = true,
                            Name = "Handmade Rubber Towels",
                            SellPrice = 51.590000000000003,
                            Sku = "ffhbegnhypbo"
                        },
                        new
                        {
                            Id = new Guid("7adee555-c402-4d6c-c4a6-d6143aefdd8a"),
                            BasePrice = 350.29000000000002,
                            Description = "Eligendi est vitae est saepe.\nEt et deserunt excepturi voluptatem sint ducimus officiis ut et.\nAperiam voluptas sint.\nRepellat minima id dolores consequatur fugit.",
                            Image = "https://picsum.photos/640/480/?image=18",
                            InStock = false,
                            Name = "Gorgeous Granite Bike",
                            SellPrice = 106.5,
                            Sku = "uvytkqan"
                        },
                        new
                        {
                            Id = new Guid("012d6893-a8d3-a776-dde1-aa0dda910d2a"),
                            BasePrice = 443.22000000000003,
                            Description = "Est et ratione atque amet.\nId vel recusandae unde.\nEt consequatur eveniet nam sint aut.\nEum cupiditate sit voluptas quia commodi quibusdam officiis illum.\nEst et enim quisquam culpa aut nisi ducimus molestias veniam.",
                            Image = "https://picsum.photos/640/480/?image=280",
                            InStock = true,
                            Name = "Awesome Frozen Pizza",
                            SellPrice = 902.42999999999995,
                            Sku = "wchywcoup"
                        },
                        new
                        {
                            Id = new Guid("5511f169-20a5-8e7a-9811-f6d46564b1ec"),
                            BasePrice = 151.44,
                            Description = "Nisi tenetur quos dolorum dolore veniam.\nIste assumenda sed saepe aut ducimus laudantium incidunt.\nPossimus voluptatem eius sunt.\nRerum voluptatem sit animi sit inventore molestiae.\nPraesentium et molestiae et.",
                            Image = "https://picsum.photos/640/480/?image=650",
                            InStock = false,
                            Name = "Intelligent Concrete Pizza",
                            SellPrice = 141.28,
                            Sku = "qvmlpoqzcwy"
                        },
                        new
                        {
                            Id = new Guid("a4459622-002d-e690-719d-bdac177f2cf3"),
                            BasePrice = 737.89999999999998,
                            Description = "Fugiat consectetur et quia ea omnis ipsa.\nEt magnam illo.\nDeleniti esse ut et itaque iste provident.\nUt molestiae doloremque omnis.\nProvident dolorem reiciendis et omnis dolores recusandae fugit quae non.",
                            Image = "https://picsum.photos/640/480/?image=178",
                            InStock = true,
                            Name = "Ergonomic Concrete Pants",
                            SellPrice = 415.37,
                            Sku = "icsqezahssll"
                        },
                        new
                        {
                            Id = new Guid("2e3a08e6-afc2-7d19-eb92-845e36d25505"),
                            BasePrice = 176.46000000000001,
                            Description = "Architecto veritatis odit in quia ratione qui exercitationem voluptatum.\nEt voluptas eaque consectetur eum.\nQuas cupiditate laborum ex aut.\nDebitis magnam et dolore autem.\nCommodi veniam perferendis eos qui voluptates rerum harum velit.",
                            Image = "https://picsum.photos/640/480/?image=447",
                            InStock = true,
                            Name = "Fantastic Granite Sausages",
                            SellPrice = 12.0,
                            Sku = "qkxjbynifo"
                        },
                        new
                        {
                            Id = new Guid("17c33da1-d92b-c22b-3fc2-c32e03e9c657"),
                            BasePrice = 807.61000000000001,
                            Description = "Repudiandae vitae consectetur eius enim deserunt inventore in eos eum.\nEa est et voluptatum aut quisquam sapiente voluptatem harum odit.\nAssumenda amet et sapiente ut ea repellat.\nRecusandae dolorum officia.",
                            Image = "https://picsum.photos/640/480/?image=304",
                            InStock = true,
                            Name = "Unbranded Wooden Sausages",
                            SellPrice = 254.88,
                            Sku = "pmofdkzjlf"
                        },
                        new
                        {
                            Id = new Guid("999b194e-bd10-f530-3b42-7c4304ed7183"),
                            BasePrice = 86.859999999999999,
                            Description = "Reprehenderit aut qui vel nemo.\nMolestiae rerum dolor magnam.\nQuae velit autem rerum minus corporis corporis nihil ex.\nIn reiciendis voluptatum sapiente laborum repellat debitis voluptas.\nSapiente quis omnis provident unde.",
                            Image = "https://picsum.photos/640/480/?image=370",
                            InStock = true,
                            Name = "Sleek Wooden Bacon",
                            SellPrice = 417.19,
                            Sku = "sqkrgpvbamvm"
                        },
                        new
                        {
                            Id = new Guid("af372266-9f98-3bf3-b208-0e76dff6089a"),
                            BasePrice = 697.25999999999999,
                            Description = "Aut voluptas eveniet temporibus est.\nDolor voluptates tempore tempore ex sed et nulla ut.\nCulpa tenetur reiciendis et commodi quia tempore fugiat.\nBeatae sit iste consequatur neque odio modi ut quibusdam.",
                            Image = "https://picsum.photos/640/480/?image=87",
                            InStock = true,
                            Name = "Incredible Plastic Chicken",
                            SellPrice = 452.66000000000003,
                            Sku = "bvidaluoc"
                        },
                        new
                        {
                            Id = new Guid("98555eca-dae8-b8d0-9a51-57322aa2d7a7"),
                            BasePrice = 266.23000000000002,
                            Description = "Occaecati est numquam neque doloribus rem cumque veritatis.\nLaborum praesentium porro inventore quia enim voluptas modi numquam et.\nPlaceat eum et eius.\nQuo sit sint ipsa ut.",
                            Image = "https://picsum.photos/640/480/?image=189",
                            InStock = false,
                            Name = "Small Plastic Ball",
                            SellPrice = 500.14999999999998,
                            Sku = "irilhbzgmr"
                        },
                        new
                        {
                            Id = new Guid("246fa4d4-d302-c13f-bba7-871ef2f2494a"),
                            BasePrice = 855.63,
                            Description = "Laudantium sapiente et sit sit alias.\nVel molestias aspernatur totam recusandae quod voluptate quidem.\nConsequatur et inventore et ut dolor et quaerat sit numquam.\nTenetur quaerat fugit ad cum voluptas at.",
                            Image = "https://picsum.photos/640/480/?image=940",
                            InStock = false,
                            Name = "Handmade Plastic Chicken",
                            SellPrice = 369.38999999999999,
                            Sku = "osiiffwpzgko"
                        },
                        new
                        {
                            Id = new Guid("5f0100bf-4ace-6b42-b92d-51982d7290c3"),
                            BasePrice = 899.63999999999999,
                            Description = "Voluptatem reiciendis aut culpa et quidem fugiat ut.\nAut id explicabo excepturi qui veritatis maxime.\nSequi quae voluptatum consequuntur totam numquam aut excepturi.\nEarum consequatur ducimus.\nEarum dolorem fugiat.\nId molestias debitis non perferendis voluptatum et incidunt ea.",
                            Image = "https://picsum.photos/640/480/?image=193",
                            InStock = false,
                            Name = "Rustic Rubber Fish",
                            SellPrice = 850.75,
                            Sku = "clfomnxmitjr"
                        },
                        new
                        {
                            Id = new Guid("a0e627be-70ee-7855-b0bd-5dc7fc68917b"),
                            BasePrice = 328.19,
                            Description = "Dolore dolor ut architecto qui eum dicta est ratione hic.\nEst quas recusandae rem illo voluptatem itaque officia.\nAutem a laborum corporis totam.\nQui et autem inventore tempora.\nLabore sunt enim enim eaque.\nQuam eaque officia.",
                            Image = "https://picsum.photos/640/480/?image=395",
                            InStock = true,
                            Name = "Fantastic Plastic Pizza",
                            SellPrice = 637.91999999999996,
                            Sku = "uhtqmzet"
                        },
                        new
                        {
                            Id = new Guid("e9236c85-e7c8-f968-dd17-cfb08c5af7b1"),
                            BasePrice = 703.63,
                            Description = "Sed ea minus.\nEt veniam qui eos et dolore.\nModi exercitationem ut officia.",
                            Image = "https://picsum.photos/640/480/?image=262",
                            InStock = true,
                            Name = "Unbranded Concrete Gloves",
                            SellPrice = 204.80000000000001,
                            Sku = "vwyocvjumfs"
                        },
                        new
                        {
                            Id = new Guid("28405536-d543-5017-8e93-3e34dd347237"),
                            BasePrice = 277.99000000000001,
                            Description = "Voluptates voluptates ullam sit hic laborum neque.\nQuisquam eaque consequatur repellendus sunt minima harum iure soluta impedit.",
                            Image = "https://picsum.photos/640/480/?image=821",
                            InStock = false,
                            Name = "Practical Cotton Bike",
                            SellPrice = 438.56,
                            Sku = "jguthmrfimpa"
                        },
                        new
                        {
                            Id = new Guid("9138d4ca-9791-ce8c-a266-b33caf8933c5"),
                            BasePrice = 286.55000000000001,
                            Description = "Sunt voluptatum sequi maiores explicabo.\nEt velit esse repudiandae dolorum qui.\nSed dolore similique soluta qui harum voluptatem eos.\nExcepturi animi commodi optio est quo et nobis asperiores eaque.\nEum repellat debitis minima ratione consequatur nostrum esse magnam.\nUllam dignissimos ut id eaque molestiae fugiat suscipit sint tempore.",
                            Image = "https://picsum.photos/640/480/?image=87",
                            InStock = true,
                            Name = "Licensed Metal Keyboard",
                            SellPrice = 870.32000000000005,
                            Sku = "ainoediskm"
                        },
                        new
                        {
                            Id = new Guid("aab77175-ebd0-5790-3f26-6585f0a55e5b"),
                            BasePrice = 345.82999999999998,
                            Description = "Tempora accusamus nam.\nEt illum quisquam voluptatem est dolores quis nesciunt quis blanditiis.",
                            Image = "https://picsum.photos/640/480/?image=180",
                            InStock = true,
                            Name = "Sleek Metal Sausages",
                            SellPrice = 699.36000000000001,
                            Sku = "pknbhcbvseji"
                        },
                        new
                        {
                            Id = new Guid("1e2187d9-034e-9ba7-2b6f-e7c18b7b6a8e"),
                            BasePrice = 142.19999999999999,
                            Description = "Omnis quae dolor dolores laudantium.\nDeserunt facere voluptatem.\nEst vitae eum quia vitae voluptas dolorem voluptas accusantium nesciunt.\nSapiente ut voluptas unde incidunt non.",
                            Image = "https://picsum.photos/640/480/?image=782",
                            InStock = false,
                            Name = "Handmade Granite Hat",
                            SellPrice = 977.88999999999999,
                            Sku = "jujttjzayt"
                        },
                        new
                        {
                            Id = new Guid("7087b731-11b5-38ab-33a6-3de335bb778f"),
                            BasePrice = 822.77999999999997,
                            Description = "Odio facere iste sit ducimus voluptates et nostrum qui quaerat.\nVoluptas qui modi aut.\nOmnis rerum aut maxime consequatur nam cumque molestiae doloribus facere.\nVoluptatibus itaque nulla dolores est commodi magnam quisquam.",
                            Image = "https://picsum.photos/640/480/?image=953",
                            InStock = true,
                            Name = "Refined Cotton Fish",
                            SellPrice = 604.38,
                            Sku = "fjtnbsjgrw"
                        },
                        new
                        {
                            Id = new Guid("ec1364da-207d-0cf6-2be1-0aeedeea0f0a"),
                            BasePrice = 967.47000000000003,
                            Description = "Natus molestiae est voluptates rem qui aut delectus sint.\nIusto aut accusantium culpa totam enim nobis.",
                            Image = "https://picsum.photos/640/480/?image=1067",
                            InStock = true,
                            Name = "Refined Concrete Fish",
                            SellPrice = 271.13,
                            Sku = "snkuhbtfydku"
                        },
                        new
                        {
                            Id = new Guid("bfaf104f-6be3-23e9-ea1f-387cb4a1a76c"),
                            BasePrice = 679.20000000000005,
                            Description = "Laudantium iste placeat nesciunt quos rem aliquam.\nVelit iusto accusamus nobis non provident officia.\nDignissimos alias ad nisi molestias accusantium velit quaerat ea voluptatem.\nEt magnam beatae tenetur.\nEveniet consequatur aut dolor et aliquam aut dolorem.",
                            Image = "https://picsum.photos/640/480/?image=256",
                            InStock = false,
                            Name = "Practical Frozen Fish",
                            SellPrice = 485.22000000000003,
                            Sku = "vgwsrzpd"
                        },
                        new
                        {
                            Id = new Guid("948021f4-7b0f-148f-47e8-425037341471"),
                            BasePrice = 117.09,
                            Description = "Voluptate dolorem ex molestiae aut doloremque odio ut et.\nNostrum explicabo ex voluptas.\nEnim non et qui earum excepturi.\nTenetur tempore nostrum eum numquam.",
                            Image = "https://picsum.photos/640/480/?image=669",
                            InStock = false,
                            Name = "Handcrafted Metal Chicken",
                            SellPrice = 475.94999999999999,
                            Sku = "eyxxidhmn"
                        },
                        new
                        {
                            Id = new Guid("aba3ee17-5475-9e7f-4564-b5d8053c3f25"),
                            BasePrice = 612.62,
                            Description = "Quisquam quam eaque qui libero reprehenderit consequatur omnis nulla.\nEnim unde cumque unde ut molestias beatae quas quibusdam.\nEum soluta et.\nLaboriosam molestiae eum omnis.\nUt ut et dignissimos reiciendis enim iure rerum.",
                            Image = "https://picsum.photos/640/480/?image=348",
                            InStock = true,
                            Name = "Refined Granite Chicken",
                            SellPrice = 648.63999999999999,
                            Sku = "xpbckbnj"
                        },
                        new
                        {
                            Id = new Guid("d565107e-b733-f680-7997-17711f50399b"),
                            BasePrice = 77.049999999999997,
                            Description = "Consequatur est accusantium vero ut explicabo molestiae eos soluta.\nDolor ut et laudantium aut enim harum a.",
                            Image = "https://picsum.photos/640/480/?image=557",
                            InStock = true,
                            Name = "Handcrafted Frozen Cheese",
                            SellPrice = 508.0,
                            Sku = "wdhetkwiw"
                        },
                        new
                        {
                            Id = new Guid("849be868-2b5a-392d-c624-c3b40675853f"),
                            BasePrice = 386.02999999999997,
                            Description = "Officia et ut aut vel.\nQuis rerum suscipit inventore maxime qui repellendus totam vel.\nDolorem quod eligendi omnis ipsum ea saepe et.",
                            Image = "https://picsum.photos/640/480/?image=258",
                            InStock = true,
                            Name = "Unbranded Metal Pizza",
                            SellPrice = 458.63,
                            Sku = "olvqsezlg"
                        },
                        new
                        {
                            Id = new Guid("82562760-25bd-ce40-1727-36aea3f07bc3"),
                            BasePrice = 40.090000000000003,
                            Description = "Ut dolorem qui incidunt fugit illo vitae.\nVoluptas modi omnis est libero perspiciatis.\nNon molestiae iste animi exercitationem quia occaecati assumenda suscipit.\nMolestias sunt illum alias a et laudantium.\nPlaceat occaecati corrupti et dignissimos laboriosam animi consequatur placeat.\nAut natus explicabo aut quis sequi aut velit.",
                            Image = "https://picsum.photos/640/480/?image=393",
                            InStock = true,
                            Name = "Licensed Metal Sausages",
                            SellPrice = 340.44,
                            Sku = "haeppwxpbyt"
                        },
                        new
                        {
                            Id = new Guid("1da9e4de-9c1f-33ab-fefd-7f5ceb7c0d42"),
                            BasePrice = 801.17999999999995,
                            Description = "Accusantium beatae et.\nExcepturi optio sunt rerum id quaerat natus.\nReiciendis non est.\nConsequatur voluptates quis omnis non voluptate.\nQuos non et ut saepe ut excepturi quia aut.",
                            Image = "https://picsum.photos/640/480/?image=576",
                            InStock = false,
                            Name = "Incredible Soft Towels",
                            SellPrice = 956.51999999999998,
                            Sku = "acphidxzgvmt"
                        },
                        new
                        {
                            Id = new Guid("4adff065-be8e-7943-3a27-7f14aab9a9fe"),
                            BasePrice = 217.05000000000001,
                            Description = "Necessitatibus omnis odio qui est molestias a dolorum veniam.\nAliquam illum quod consequatur hic veritatis voluptatem architecto.\nUt harum facilis ut consequatur magni harum doloribus.\nQuae ratione aut.",
                            Image = "https://picsum.photos/640/480/?image=619",
                            InStock = false,
                            Name = "Gorgeous Rubber Shirt",
                            SellPrice = 749.63999999999999,
                            Sku = "nhyhhsxfwk"
                        },
                        new
                        {
                            Id = new Guid("2f912ec4-94ea-46d2-be66-0b1b9bef6260"),
                            BasePrice = 757.15999999999997,
                            Description = "Et sed repudiandae minus sed odit et quia velit.\nUt sit suscipit aspernatur nihil quaerat.\nSunt dicta qui corporis distinctio.\nNulla aliquam modi sit aut cupiditate.\nIste earum non beatae corrupti distinctio vitae occaecati temporibus quis.\nAut aperiam quidem est repudiandae.",
                            Image = "https://picsum.photos/640/480/?image=632",
                            InStock = false,
                            Name = "Rustic Wooden Salad",
                            SellPrice = 36.079999999999998,
                            Sku = "zfliyyxz"
                        },
                        new
                        {
                            Id = new Guid("de3fc567-ec93-e4d6-b4ff-63fa31ec0e9c"),
                            BasePrice = 310.69999999999999,
                            Description = "Quos quidem voluptatem corporis dolorum sunt.\nVelit quia impedit sint temporibus.\nAmet ut eveniet ab ipsam laudantium.\nQuod qui fugiat id aliquid voluptatem labore ipsum repudiandae nobis.",
                            Image = "https://picsum.photos/640/480/?image=232",
                            InStock = false,
                            Name = "Handmade Wooden Bacon",
                            SellPrice = 270.48000000000002,
                            Sku = "igifquustoj"
                        },
                        new
                        {
                            Id = new Guid("6a6af56e-7db5-f730-85a8-c4541622564e"),
                            BasePrice = 881.63,
                            Description = "Aut qui placeat.\nRerum voluptas autem.\nAut ipsum dolore eum rerum non eum aliquid.",
                            Image = "https://picsum.photos/640/480/?image=188",
                            InStock = false,
                            Name = "Unbranded Wooden Gloves",
                            SellPrice = 626.53999999999996,
                            Sku = "pahqwudmhchi"
                        },
                        new
                        {
                            Id = new Guid("4b2bc2c6-3d7d-1b63-92c4-99759cc41016"),
                            BasePrice = 774.25,
                            Description = "Repellat voluptas sapiente.\nEa sed fugiat optio quod.\nModi odit earum quis maiores.\nMagni quae voluptatibus odio laudantium et.\nNon quis aut quo nam eveniet et sed placeat.",
                            Image = "https://picsum.photos/640/480/?image=162",
                            InStock = false,
                            Name = "Tasty Fresh Sausages",
                            SellPrice = 318.05000000000001,
                            Sku = "mrqiuubayjvp"
                        },
                        new
                        {
                            Id = new Guid("465fdd4d-f30b-64de-056a-a6515741d861"),
                            BasePrice = 591.02999999999997,
                            Description = "Minima quod quos in natus id aut aut quidem vel.\nAut est perspiciatis.\nIpsum corporis ut maxime explicabo.",
                            Image = "https://picsum.photos/640/480/?image=5",
                            InStock = false,
                            Name = "Practical Rubber Salad",
                            SellPrice = 386.19,
                            Sku = "gputlzbo"
                        },
                        new
                        {
                            Id = new Guid("5ad5c4fd-5436-9530-5f06-b8bdb7c30ddb"),
                            BasePrice = 236.83000000000001,
                            Description = "Modi odit vero maxime iure labore ex culpa earum excepturi.\nRerum dolore natus aut temporibus blanditiis repudiandae.\nIusto ut et illum aut quasi nesciunt eos.\nEst ipsum illo.\nQuam consequatur qui quia tenetur at aliquam ut.\nVero minima earum maxime tenetur consectetur occaecati velit autem eligendi.",
                            Image = "https://picsum.photos/640/480/?image=965",
                            InStock = true,
                            Name = "Small Fresh Table",
                            SellPrice = 265.57999999999998,
                            Sku = "odyxebznjcdb"
                        },
                        new
                        {
                            Id = new Guid("4cff4f61-08f9-72b1-65d0-dc4fc8e7eba5"),
                            BasePrice = 940.61000000000001,
                            Description = "Distinctio explicabo accusamus provident voluptas aperiam adipisci similique.\nUt sed et eos nesciunt laboriosam enim.\nMaiores nobis ut reprehenderit voluptatem qui qui.\nQuisquam dolor ut quibusdam praesentium exercitationem et provident corporis.\nEt omnis sint officia id exercitationem omnis.",
                            Image = "https://picsum.photos/640/480/?image=84",
                            InStock = false,
                            Name = "Sleek Fresh Soap",
                            SellPrice = 302.08999999999997,
                            Sku = "stscfqudrei"
                        },
                        new
                        {
                            Id = new Guid("42f71f88-be56-1658-eea4-e5fcec57c529"),
                            BasePrice = 581.46000000000004,
                            Description = "Qui exercitationem quos et minus quisquam sunt nemo labore fugiat.\nLibero architecto voluptatum velit.\nVoluptate natus non vero a autem.\nMaiores molestias omnis.\nPossimus commodi deleniti ut molestiae distinctio porro error ut.\nQuis corrupti accusamus aut laboriosam provident voluptate provident veniam.",
                            Image = "https://picsum.photos/640/480/?image=229",
                            InStock = false,
                            Name = "Intelligent Rubber Sausages",
                            SellPrice = 795.34000000000003,
                            Sku = "exnwgmba"
                        },
                        new
                        {
                            Id = new Guid("dc54d0ae-cf45-e534-2c94-7312b58c9139"),
                            BasePrice = 848.09000000000003,
                            Description = "Nobis at voluptas enim tenetur ipsam molestiae voluptates.\nAb tenetur officiis earum est.\nQuos rerum quam doloribus officia facilis nemo rerum tempora soluta.",
                            Image = "https://picsum.photos/640/480/?image=951",
                            InStock = false,
                            Name = "Awesome Frozen Pizza",
                            SellPrice = 627.04999999999995,
                            Sku = "ecisxweuja"
                        },
                        new
                        {
                            Id = new Guid("ba03574e-dbbf-499f-ae10-41bfb3274c82"),
                            BasePrice = 488.74000000000001,
                            Description = "Omnis qui unde culpa.\nSunt nulla maxime aspernatur.\nEst ut et minima ipsa.\nQuia qui cumque deleniti.\nConsequatur assumenda unde laboriosam distinctio.",
                            Image = "https://picsum.photos/640/480/?image=838",
                            InStock = false,
                            Name = "Unbranded Frozen Gloves",
                            SellPrice = 876.65999999999997,
                            Sku = "wzfzfvcfni"
                        },
                        new
                        {
                            Id = new Guid("f1b7ef53-0c81-56e3-45d4-ff57e08c8fa7"),
                            BasePrice = 412.23000000000002,
                            Description = "Nihil ipsum optio voluptatum.\nAnimi velit et non sint.\nTotam eos distinctio repellendus.\nOdio consequuntur quia incidunt recusandae at facere.\nEt ab fuga distinctio.",
                            Image = "https://picsum.photos/640/480/?image=490",
                            InStock = false,
                            Name = "Handcrafted Granite Pants",
                            SellPrice = 911.73000000000002,
                            Sku = "urdsjwupvk"
                        },
                        new
                        {
                            Id = new Guid("27a25346-af54-aab9-f094-8620fe7aeb52"),
                            BasePrice = 810.25999999999999,
                            Description = "Dicta illo fugiat sunt maiores non dolor quo quisquam.\nAut error consequatur soluta dolorem esse voluptatibus laboriosam natus fugit.\nMaiores ut molestiae reiciendis soluta sit perspiciatis molestiae laborum blanditiis.\nVero omnis quae aliquam.\nEt natus distinctio animi suscipit impedit esse maxime.",
                            Image = "https://picsum.photos/640/480/?image=435",
                            InStock = true,
                            Name = "Ergonomic Fresh Computer",
                            SellPrice = 283.48000000000002,
                            Sku = "milvlgbefty"
                        },
                        new
                        {
                            Id = new Guid("96077075-a36d-1054-3084-7a7ef66e195b"),
                            BasePrice = 878.51999999999998,
                            Description = "Possimus maiores rerum assumenda tenetur sed.\nAut rerum et magnam.\nQui incidunt iure consequatur aliquam.\nFacere et porro omnis.\nDolore dolorum qui cupiditate aut nisi tempora consequatur qui.",
                            Image = "https://picsum.photos/640/480/?image=1071",
                            InStock = true,
                            Name = "Incredible Steel Cheese",
                            SellPrice = 527.65999999999997,
                            Sku = "qwdgyibp"
                        },
                        new
                        {
                            Id = new Guid("fdc39124-2b0a-b11b-18fb-7260523b5d34"),
                            BasePrice = 767.08000000000004,
                            Description = "Nemo est corrupti sed ad reiciendis quia tenetur dolorem.\nDignissimos magnam voluptates impedit est eum.\nConsequuntur aut ut modi blanditiis doloribus maiores recusandae et.\nEa hic est qui quasi commodi quidem est quod.\nQuas et praesentium earum ut voluptatem laborum qui occaecati rerum.\nEos ullam hic aut odio.",
                            Image = "https://picsum.photos/640/480/?image=705",
                            InStock = true,
                            Name = "Awesome Metal Keyboard",
                            SellPrice = 755.04999999999995,
                            Sku = "czygljbhzyv"
                        },
                        new
                        {
                            Id = new Guid("292dcec2-bd51-11ad-aaae-8d4cac0aa768"),
                            BasePrice = 204.12,
                            Description = "Culpa et voluptatem amet quidem voluptatem cum.\nSit fugiat nisi voluptas qui architecto dolore sunt.",
                            Image = "https://picsum.photos/640/480/?image=1011",
                            InStock = false,
                            Name = "Intelligent Granite Ball",
                            SellPrice = 512.02999999999997,
                            Sku = "paiwoxtfziou"
                        },
                        new
                        {
                            Id = new Guid("00cf9611-15bf-fbaa-c181-aac13635605c"),
                            BasePrice = 32.420000000000002,
                            Description = "Beatae harum deserunt fugit sapiente ut explicabo hic quas.\nQuia non natus quos ratione rerum qui.\nEst cumque vel voluptatem et pariatur sint.\nEnim aspernatur eaque et rerum nulla dolore omnis natus vel.\nVeritatis numquam maxime consequatur cumque.\nHic ipsa omnis ratione ut possimus sit odio error.",
                            Image = "https://picsum.photos/640/480/?image=212",
                            InStock = false,
                            Name = "Unbranded Frozen Table",
                            SellPrice = 165.88,
                            Sku = "xvzxitjqp"
                        },
                        new
                        {
                            Id = new Guid("268c562c-63de-c825-f579-e0914424b344"),
                            BasePrice = 145.41999999999999,
                            Description = "Quae facilis exercitationem magnam nisi vel culpa sed excepturi.\nVoluptatem aut minus.\nMolestiae unde fugiat quidem officia perferendis soluta.",
                            Image = "https://picsum.photos/640/480/?image=768",
                            InStock = true,
                            Name = "Small Plastic Salad",
                            SellPrice = 622.40999999999997,
                            Sku = "mzkihkrcq"
                        },
                        new
                        {
                            Id = new Guid("a149b5f0-efe7-2917-b4cd-557be823473d"),
                            BasePrice = 560.57000000000005,
                            Description = "Et magni rerum dolorum earum debitis voluptas molestiae.\nAsperiores enim eum doloribus in consectetur.",
                            Image = "https://picsum.photos/640/480/?image=750",
                            InStock = true,
                            Name = "Rustic Soft Pizza",
                            SellPrice = 496.54000000000002,
                            Sku = "bclnqgzvpenv"
                        },
                        new
                        {
                            Id = new Guid("6bb53ab6-daf9-45ae-96b1-f3c9458d1afe"),
                            BasePrice = 295.81999999999999,
                            Description = "Architecto quo est aperiam accusantium aut ut voluptate.\nAliquam voluptatibus dignissimos molestiae sunt dolorum non.\nEst sit quis quia.\nEaque totam consectetur qui nobis.\nMagni facere facere et aspernatur voluptatem occaecati.",
                            Image = "https://picsum.photos/640/480/?image=290",
                            InStock = false,
                            Name = "Licensed Rubber Fish",
                            SellPrice = 939.45000000000005,
                            Sku = "cxurmzlbdeu"
                        },
                        new
                        {
                            Id = new Guid("80c5ae84-7d79-1f16-8889-5725a25f2df0"),
                            BasePrice = 901.16999999999996,
                            Description = "Tenetur commodi enim architecto eligendi occaecati ut.\nQuibusdam voluptas aliquid minima aut repudiandae quia ex blanditiis voluptatem.\nDicta sed quo sit eum est aut.\nNesciunt maxime rerum.\nFugiat et et saepe minus esse.\nQuia ex consequuntur.",
                            Image = "https://picsum.photos/640/480/?image=638",
                            InStock = false,
                            Name = "Refined Granite Chair",
                            SellPrice = 927.83000000000004,
                            Sku = "irkmczlpnq"
                        },
                        new
                        {
                            Id = new Guid("a5cd14c2-3cf6-0f70-ab15-ec01702ced3d"),
                            BasePrice = 370.77999999999997,
                            Description = "Sed et porro harum velit.\nNesciunt neque tempora et et officiis.\nSit dolorem qui tenetur atque expedita natus aut qui omnis.\nMolestiae totam quis ullam laudantium.",
                            Image = "https://picsum.photos/640/480/?image=818",
                            InStock = false,
                            Name = "Gorgeous Fresh Chair",
                            SellPrice = 604.90999999999997,
                            Sku = "plmahsbyvb"
                        },
                        new
                        {
                            Id = new Guid("aee7953a-eda0-5987-5bc3-a470c0837233"),
                            BasePrice = 350.94,
                            Description = "Quis ipsa dolore corporis minus aliquid atque.\nSed sint optio.",
                            Image = "https://picsum.photos/640/480/?image=389",
                            InStock = false,
                            Name = "Practical Soft Chair",
                            SellPrice = 182.22,
                            Sku = "vamxwesmfwrq"
                        },
                        new
                        {
                            Id = new Guid("ee25b3ea-a13c-c17f-6047-6363f28889ec"),
                            BasePrice = 600.30999999999995,
                            Description = "Et sapiente non aut ut.\nMolestiae veritatis necessitatibus cumque.\nAutem nesciunt molestias perspiciatis voluptatem voluptatibus voluptatibus non ipsam.",
                            Image = "https://picsum.photos/640/480/?image=29",
                            InStock = true,
                            Name = "Gorgeous Cotton Salad",
                            SellPrice = 363.20999999999998,
                            Sku = "mucwiioyn"
                        },
                        new
                        {
                            Id = new Guid("1e8c7ab6-4663-f6ea-7f97-778426e65a94"),
                            BasePrice = 829.78999999999996,
                            Description = "Ut est ipsum eveniet et et rem libero consectetur debitis.\nNemo labore rerum quia et.\nSoluta qui soluta occaecati tempora quia.\nFugiat maiores accusamus optio qui ea.\nEum occaecati voluptatum quasi sed qui.\nRerum temporibus adipisci.",
                            Image = "https://picsum.photos/640/480/?image=950",
                            InStock = true,
                            Name = "Rustic Soft Mouse",
                            SellPrice = 264.37,
                            Sku = "mxwnhwfjs"
                        },
                        new
                        {
                            Id = new Guid("7193ca67-3fcb-7631-79ee-1b9bc4db2b72"),
                            BasePrice = 508.31999999999999,
                            Description = "Maiores et praesentium autem dolorum ut facilis tenetur.\nUt in nemo sit et sequi.\nAmet voluptas voluptatem neque rem et quasi et aspernatur.\nQuia architecto et omnis impedit est eligendi fugit.",
                            Image = "https://picsum.photos/640/480/?image=178",
                            InStock = true,
                            Name = "Refined Soft Cheese",
                            SellPrice = 364.97000000000003,
                            Sku = "npavkcmuq"
                        },
                        new
                        {
                            Id = new Guid("5ebdadaf-c5f3-7144-f015-edbf319b1cc1"),
                            BasePrice = 554.20000000000005,
                            Description = "Qui in nulla aperiam.\nVelit labore deserunt.\nQuasi dolorem molestias cumque.\nEius culpa tempora nemo nesciunt sint atque iste qui.\nVeritatis ipsa facilis consequatur debitis et.\nEst ut sequi aspernatur.",
                            Image = "https://picsum.photos/640/480/?image=636",
                            InStock = false,
                            Name = "Rustic Fresh Tuna",
                            SellPrice = 747.58000000000004,
                            Sku = "yygubrntnhyn"
                        },
                        new
                        {
                            Id = new Guid("99471579-028d-4aa3-9b0a-15663990983d"),
                            BasePrice = 842.57000000000005,
                            Description = "Nulla dignissimos repudiandae deserunt dolore odit voluptatem dolorem iure eum.\nMaiores nihil sint doloremque velit provident est et.\nVelit beatae consequatur numquam atque voluptatem deleniti.",
                            Image = "https://picsum.photos/640/480/?image=207",
                            InStock = false,
                            Name = "Incredible Cotton Car",
                            SellPrice = 610.89999999999998,
                            Sku = "bxfhdnfrm"
                        },
                        new
                        {
                            Id = new Guid("a3c19545-6baf-dc98-49e4-22fafc63ecb0"),
                            BasePrice = 413.13999999999999,
                            Description = "Sapiente illo eum esse provident aperiam at asperiores in est.\nEst assumenda rem veniam ipsum sit sint ipsum qui eaque.\nOccaecati nam occaecati veniam.\nVel eveniet incidunt asperiores dolorem.",
                            Image = "https://picsum.photos/640/480/?image=987",
                            InStock = false,
                            Name = "Small Plastic Table",
                            SellPrice = 305.81999999999999,
                            Sku = "pmzfbzwriy"
                        },
                        new
                        {
                            Id = new Guid("929a9850-adb1-dfbc-66f9-874b3bcb23e6"),
                            BasePrice = 681.29999999999995,
                            Description = "Facere quam sed eum recusandae consequatur nulla.\nEnim deleniti sunt tempora similique sit non alias enim dicta.\nSoluta eum assumenda nam culpa.\nIpsam temporibus placeat beatae sit fugiat.\nBeatae incidunt suscipit delectus ipsa quasi.\nDelectus alias suscipit quo maiores nobis nisi placeat.",
                            Image = "https://picsum.photos/640/480/?image=683",
                            InStock = false,
                            Name = "Refined Concrete Chair",
                            SellPrice = 444.66000000000003,
                            Sku = "bjrbfuxnxl"
                        },
                        new
                        {
                            Id = new Guid("25629ef7-6bf8-5ee9-97d3-e6bacb9ddd5b"),
                            BasePrice = 606.5,
                            Description = "Qui labore illo ratione aperiam.\nEum qui eaque voluptatem facilis.\nOmnis repudiandae non totam sint quibusdam necessitatibus est.\nSint repellendus qui architecto aut doloremque sapiente voluptatibus reiciendis.\nRerum ipsa magnam nihil eveniet aut.",
                            Image = "https://picsum.photos/640/480/?image=530",
                            InStock = false,
                            Name = "Ergonomic Cotton Towels",
                            SellPrice = 734.66999999999996,
                            Sku = "zetmsjfcsare"
                        },
                        new
                        {
                            Id = new Guid("19f5fbc3-f676-197d-412e-619106037fe9"),
                            BasePrice = 731.44000000000005,
                            Description = "Itaque reprehenderit minima quasi ut a enim commodi vitae sapiente.\nEligendi molestiae vel dolore modi eos et non iusto.\nDeserunt perspiciatis et est sequi eaque expedita et ut corrupti.\nEa veritatis nulla beatae qui incidunt facilis.",
                            Image = "https://picsum.photos/640/480/?image=112",
                            InStock = true,
                            Name = "Awesome Frozen Bacon",
                            SellPrice = 878.20000000000005,
                            Sku = "kwykyxmnte"
                        },
                        new
                        {
                            Id = new Guid("449f432b-acb7-73f7-34bd-4c85094abe11"),
                            BasePrice = 185.84999999999999,
                            Description = "A occaecati ut quis quam amet culpa.\nImpedit sunt explicabo veniam.",
                            Image = "https://picsum.photos/640/480/?image=110",
                            InStock = false,
                            Name = "Awesome Cotton Shirt",
                            SellPrice = 852.42999999999995,
                            Sku = "txdlfbycxg"
                        },
                        new
                        {
                            Id = new Guid("624af5ea-52c7-45bb-4650-ad9d6658cf0e"),
                            BasePrice = 235.27000000000001,
                            Description = "Consequatur dolor minima ducimus quia.\nTempore excepturi ut ullam molestias sapiente perferendis.\nAliquid suscipit dolorem voluptatem molestias sed rem dolor dolorem.\nQuis ipsum dignissimos eveniet perspiciatis.\nError rerum sequi dolores occaecati asperiores.",
                            Image = "https://picsum.photos/640/480/?image=287",
                            InStock = false,
                            Name = "Incredible Metal Chips",
                            SellPrice = 983.37,
                            Sku = "bbchqlfbwpf"
                        },
                        new
                        {
                            Id = new Guid("1e5d342d-a34e-fbc0-d1fb-c6229274f719"),
                            BasePrice = 495.88999999999999,
                            Description = "A unde et cupiditate fuga ratione.\nIllo voluptatem qui illo corrupti quidem.\nVoluptatem maxime repellat sequi numquam facere itaque ullam tenetur doloremque.",
                            Image = "https://picsum.photos/640/480/?image=967",
                            InStock = false,
                            Name = "Sleek Granite Soap",
                            SellPrice = 973.44000000000005,
                            Sku = "nhgwbcoicj"
                        },
                        new
                        {
                            Id = new Guid("5a24b0fa-ef28-f9da-f534-c09543727bec"),
                            BasePrice = 86.349999999999994,
                            Description = "Itaque nam sit aut quod ut distinctio.\nIn rerum sunt tempora et.\nVel consequatur amet quod quasi asperiores in.\nLibero ducimus ab est dicta blanditiis.\nPraesentium est aut et doloribus quam cum veritatis occaecati.",
                            Image = "https://picsum.photos/640/480/?image=212",
                            InStock = true,
                            Name = "Handmade Soft Keyboard",
                            SellPrice = 417.41000000000003,
                            Sku = "tamfmrvmyl"
                        },
                        new
                        {
                            Id = new Guid("f0c9b235-6b3e-6581-0a47-5c62031a2045"),
                            BasePrice = 291.37,
                            Description = "Assumenda impedit qui.\nEt hic fugiat maxime accusantium dolorum.\nModi odit aliquid.\nEum ut autem et aut perferendis quia.",
                            Image = "https://picsum.photos/640/480/?image=219",
                            InStock = false,
                            Name = "Ergonomic Wooden Pizza",
                            SellPrice = 699.02999999999997,
                            Sku = "gsuunwagbdb"
                        },
                        new
                        {
                            Id = new Guid("7163f3fc-2d04-0694-6491-54becf8b63f8"),
                            BasePrice = 220.31,
                            Description = "Illum atque nam sit et laboriosam dolorem.\nAut dolore ut numquam sit pariatur.\nVoluptatem vero et fugiat.\nNam ipsum omnis commodi voluptates dolor debitis provident.",
                            Image = "https://picsum.photos/640/480/?image=415",
                            InStock = false,
                            Name = "Intelligent Rubber Mouse",
                            SellPrice = 640.08000000000004,
                            Sku = "rakziegkvbxl"
                        },
                        new
                        {
                            Id = new Guid("79a164ed-622e-59bc-de7a-d27978786d03"),
                            BasePrice = 521.29999999999995,
                            Description = "Sequi a illo quis et sed.\nCulpa ea dignissimos.\nItaque mollitia voluptatem repellendus.\nDignissimos suscipit aut et dolores et adipisci numquam.\nDolore nostrum est reprehenderit earum et quia placeat.\nEx ipsa accusantium necessitatibus laboriosam eum minima voluptates repellat.",
                            Image = "https://picsum.photos/640/480/?image=220",
                            InStock = false,
                            Name = "Handcrafted Concrete Table",
                            SellPrice = 897.34000000000003,
                            Sku = "mexxkbrgw"
                        },
                        new
                        {
                            Id = new Guid("8c0e9142-44e0-7b29-600b-014e5d05696d"),
                            BasePrice = 570.03999999999996,
                            Description = "Corrupti harum culpa iure in autem quisquam molestias sit dolorum.\nIusto rem tempora nesciunt.",
                            Image = "https://picsum.photos/640/480/?image=215",
                            InStock = true,
                            Name = "Incredible Plastic Soap",
                            SellPrice = 82.299999999999997,
                            Sku = "remexvrivod"
                        },
                        new
                        {
                            Id = new Guid("20ada9d1-27d4-96b7-7150-7041201c899a"),
                            BasePrice = 338.06999999999999,
                            Description = "Dolore voluptas ea.\nModi iure nihil hic ut.\nQui explicabo nisi ullam.\nDolor commodi quia est odit aut est cum porro.",
                            Image = "https://picsum.photos/640/480/?image=335",
                            InStock = false,
                            Name = "Intelligent Wooden Fish",
                            SellPrice = 563.47000000000003,
                            Sku = "wxpbxqsxwxbw"
                        },
                        new
                        {
                            Id = new Guid("efe9d55b-d72b-3c63-4257-f6c7e494efe6"),
                            BasePrice = 985.12,
                            Description = "Officia sint voluptatem itaque laboriosam ea incidunt delectus.\nVoluptatibus blanditiis suscipit cum hic aut dicta.\nAutem similique excepturi consequatur autem modi voluptatem quia.\nQui est ipsam ut sunt aspernatur voluptas.",
                            Image = "https://picsum.photos/640/480/?image=1040",
                            InStock = false,
                            Name = "Rustic Fresh Keyboard",
                            SellPrice = 26.100000000000001,
                            Sku = "mvxiiyrxvojt"
                        },
                        new
                        {
                            Id = new Guid("f7a27557-1f75-4562-392d-57627919c8e6"),
                            BasePrice = 110.95999999999999,
                            Description = "Iste sapiente consequuntur explicabo eaque nihil voluptas.\nConsequatur facilis maiores vero.\nQui voluptatem repudiandae temporibus.\nVoluptatem aspernatur consequuntur nulla dignissimos cupiditate est saepe.\nEsse minus temporibus expedita eos temporibus nulla fugit.\nVoluptatem delectus aut sint enim.",
                            Image = "https://picsum.photos/640/480/?image=456",
                            InStock = false,
                            Name = "Sleek Rubber Shoes",
                            SellPrice = 22.73,
                            Sku = "weybovjwjex"
                        },
                        new
                        {
                            Id = new Guid("0a288fc9-dd09-e65e-c10a-efbf8f8b1598"),
                            BasePrice = 312.04000000000002,
                            Description = "Iusto et dolores porro repellendus quibusdam.\nExcepturi aliquid corrupti.\nEt fugiat laboriosam omnis.",
                            Image = "https://picsum.photos/640/480/?image=412",
                            InStock = false,
                            Name = "Handmade Wooden Chicken",
                            SellPrice = 543.90999999999997,
                            Sku = "iuewkkkpy"
                        },
                        new
                        {
                            Id = new Guid("60407fbf-9d03-7469-d2b5-5cae5ce40e7f"),
                            BasePrice = 514.75,
                            Description = "Nostrum hic doloribus qui fugit facilis et exercitationem ut doloremque.\nCommodi necessitatibus vero necessitatibus.\nQuis aut ab fugiat quia odit ullam.",
                            Image = "https://picsum.photos/640/480/?image=689",
                            InStock = false,
                            Name = "Incredible Metal Computer",
                            SellPrice = 975.13999999999999,
                            Sku = "jfvmjgmtls"
                        },
                        new
                        {
                            Id = new Guid("ecb5964d-6c81-1b55-fc28-b870b00b1bd8"),
                            BasePrice = 900.34000000000003,
                            Description = "Quia ex enim incidunt quidem voluptatem ut qui.\nDebitis eos placeat animi error quia quis est eum ea.\nNostrum qui perferendis qui dignissimos qui aperiam.\nAccusantium incidunt ea qui repellat amet.\nBlanditiis officia quas.\nVoluptatem est totam quaerat.",
                            Image = "https://picsum.photos/640/480/?image=748",
                            InStock = false,
                            Name = "Rustic Plastic Mouse",
                            SellPrice = 470.36000000000001,
                            Sku = "qkpnuhtze"
                        },
                        new
                        {
                            Id = new Guid("3e42cfc0-60dd-f669-6b3e-b81401afcf33"),
                            BasePrice = 532.92999999999995,
                            Description = "Velit nulla reiciendis.\nUt nesciunt voluptatum rerum molestiae eum et amet.\nDolores totam nihil quia odio.\nVelit provident et culpa ipsam sed nihil.\nQuos dolor dolores.",
                            Image = "https://picsum.photos/640/480/?image=10",
                            InStock = false,
                            Name = "Intelligent Concrete Mouse",
                            SellPrice = 906.71000000000004,
                            Sku = "kvjnslzma"
                        },
                        new
                        {
                            Id = new Guid("9c695564-e8f9-d7ae-97d5-f968512c97c6"),
                            BasePrice = 165.84,
                            Description = "A sed quibusdam porro occaecati incidunt.\nQuaerat suscipit est veritatis nam sit dicta sed ut minima.\nAd omnis velit quos cumque blanditiis nesciunt eum non rerum.\nQuo necessitatibus et.\nCorporis voluptas magnam sunt dolore.",
                            Image = "https://picsum.photos/640/480/?image=686",
                            InStock = true,
                            Name = "Handcrafted Steel Table",
                            SellPrice = 348.42000000000002,
                            Sku = "ulqkypeytkqh"
                        },
                        new
                        {
                            Id = new Guid("5a781ffd-64ec-5810-e826-daa7b0dcce32"),
                            BasePrice = 483.50999999999999,
                            Description = "Officiis velit dolorem a sequi sapiente.\nQuo accusamus nihil officia porro autem ipsa aut.\nMollitia odit amet quia impedit nisi provident tempore repudiandae molestiae.\nOmnis error ea natus hic repellendus sit consectetur et.\nSuscipit at corrupti sed.\nQuis autem ducimus est.",
                            Image = "https://picsum.photos/640/480/?image=352",
                            InStock = false,
                            Name = "Refined Steel Bacon",
                            SellPrice = 445.94,
                            Sku = "nkqdqnvdhdf"
                        },
                        new
                        {
                            Id = new Guid("3dda1f0f-769d-dfa4-f96a-9c68a2ae47c3"),
                            BasePrice = 505.99000000000001,
                            Description = "Unde dolores officiis.\nEt odio ut maiores ut saepe aut debitis aut.",
                            Image = "https://picsum.photos/640/480/?image=339",
                            InStock = true,
                            Name = "Incredible Cotton Mouse",
                            SellPrice = 424.47000000000003,
                            Sku = "qvyfebjfwts"
                        },
                        new
                        {
                            Id = new Guid("955e0442-3b8a-4d5c-40b7-c6a8b7616a4f"),
                            BasePrice = 84.409999999999997,
                            Description = "Excepturi enim animi dolor voluptates.\nExcepturi omnis in.",
                            Image = "https://picsum.photos/640/480/?image=706",
                            InStock = true,
                            Name = "Tasty Cotton Hat",
                            SellPrice = 960.51999999999998,
                            Sku = "drpncajlnvg"
                        },
                        new
                        {
                            Id = new Guid("082d63e0-3116-83a5-3cf3-318fce685d44"),
                            BasePrice = 763.88,
                            Description = "Qui fuga quae quae consequatur voluptatem.\nCumque asperiores quia corrupti repellat.\nVero cumque voluptas fugiat.\nNihil hic repellendus delectus.",
                            Image = "https://picsum.photos/640/480/?image=585",
                            InStock = false,
                            Name = "Small Rubber Fish",
                            SellPrice = 223.31999999999999,
                            Sku = "osgouoofdty"
                        },
                        new
                        {
                            Id = new Guid("57c18b50-b8a0-cb88-42e8-a713c87888d5"),
                            BasePrice = 995.60000000000002,
                            Description = "Sapiente veritatis natus numquam alias est eos.\nSint debitis ullam voluptate quia aut voluptas.\nPlaceat ea inventore labore.\nQuidem quo soluta dolores quasi.\nVoluptate hic hic.\nMolestiae aut hic nam.",
                            Image = "https://picsum.photos/640/480/?image=32",
                            InStock = false,
                            Name = "Tasty Frozen Keyboard",
                            SellPrice = 540.94000000000005,
                            Sku = "jxfjzdalpias"
                        },
                        new
                        {
                            Id = new Guid("6d762127-1628-0588-0b80-1a02d1fe3079"),
                            BasePrice = 211.88,
                            Description = "Est at tempore.\nQuia voluptas reiciendis minus eos ipsum sed molestiae ducimus.\nMagni rerum enim est aut qui qui.",
                            Image = "https://picsum.photos/640/480/?image=535",
                            InStock = true,
                            Name = "Handcrafted Concrete Chair",
                            SellPrice = 519.52999999999997,
                            Sku = "ejwngpcdoeol"
                        },
                        new
                        {
                            Id = new Guid("f43dd0a7-f875-a15d-64ae-8e0cedec4b97"),
                            BasePrice = 522.50999999999999,
                            Description = "Omnis eius sit atque animi voluptates amet voluptas dolore.\nPossimus reiciendis est omnis.\nQuia est neque sit ratione ipsam sequi earum vel.",
                            Image = "https://picsum.photos/640/480/?image=449",
                            InStock = false,
                            Name = "Small Concrete Tuna",
                            SellPrice = 995.28999999999996,
                            Sku = "kbhzoshfuc"
                        },
                        new
                        {
                            Id = new Guid("f9b86542-3421-4ae9-0a43-f387bae16872"),
                            BasePrice = 621.88,
                            Description = "Qui est earum nam veniam.\nRerum minus asperiores quia est enim.\nInventore ipsam quo dolores quibusdam quod ut qui et quidem.",
                            Image = "https://picsum.photos/640/480/?image=435",
                            InStock = true,
                            Name = "Awesome Rubber Salad",
                            SellPrice = 501.64999999999998,
                            Sku = "iroxrrcvmx"
                        },
                        new
                        {
                            Id = new Guid("2c768883-fe7d-51c9-0b3a-866880327ff2"),
                            BasePrice = 131.28999999999999,
                            Description = "Sequi quasi porro fugit non quibusdam tenetur ut.\nAliquam rerum est.\nQuis beatae unde explicabo voluptas.",
                            Image = "https://picsum.photos/640/480/?image=1019",
                            InStock = false,
                            Name = "Practical Rubber Car",
                            SellPrice = 468.23000000000002,
                            Sku = "ehqqpckrk"
                        },
                        new
                        {
                            Id = new Guid("47da461c-c1a9-0a4f-c642-a83c8edfbbbb"),
                            BasePrice = 510.30000000000001,
                            Description = "Architecto qui mollitia reiciendis voluptatem.\nQuia magnam in qui corrupti similique architecto sed reiciendis.\nDolorem necessitatibus deleniti facilis aut veritatis.",
                            Image = "https://picsum.photos/640/480/?image=671",
                            InStock = false,
                            Name = "Tasty Granite Pizza",
                            SellPrice = 837.86000000000001,
                            Sku = "dnvwaiuz"
                        },
                        new
                        {
                            Id = new Guid("65aefece-120b-76d7-1585-ee47e7a1fcf3"),
                            BasePrice = 573.60000000000002,
                            Description = "Eos hic mollitia.\nEaque molestiae nihil eos laborum asperiores quidem commodi.",
                            Image = "https://picsum.photos/640/480/?image=521",
                            InStock = true,
                            Name = "Incredible Frozen Computer",
                            SellPrice = 19.960000000000001,
                            Sku = "othzmbiku"
                        },
                        new
                        {
                            Id = new Guid("aa1b7933-3a03-b468-31d3-6b45fe0882d0"),
                            BasePrice = 642.48000000000002,
                            Description = "Omnis laborum illo dolores ex voluptatum sequi non voluptatem.\nNecessitatibus velit aut omnis fuga saepe enim.\nHarum doloribus quia ut iusto.\nEnim quam soluta repellendus sit repellat sit et.",
                            Image = "https://picsum.photos/640/480/?image=827",
                            InStock = false,
                            Name = "Sleek Cotton Mouse",
                            SellPrice = 916.27999999999997,
                            Sku = "hyryxydttk"
                        },
                        new
                        {
                            Id = new Guid("49979d68-4029-e687-e4b6-dac85c036bd9"),
                            BasePrice = 401.67000000000002,
                            Description = "Sit omnis voluptatem corrupti.\nEos corrupti sunt sit ipsa assumenda itaque.\nQuos modi corporis beatae consequatur.\nRatione pariatur laudantium.",
                            Image = "https://picsum.photos/640/480/?image=882",
                            InStock = false,
                            Name = "Fantastic Fresh Soap",
                            SellPrice = 711.17999999999995,
                            Sku = "nfaktrpoqi"
                        },
                        new
                        {
                            Id = new Guid("deeac7c3-2010-7dd8-c21c-31f3366bab8b"),
                            BasePrice = 388.16000000000003,
                            Description = "Quae optio voluptas aut sed.\nSaepe impedit neque impedit.\nId dolores ipsum dolore unde velit architecto dolorum sint consequatur.\nAut a repellat illum aut veniam.\nMolestias et temporibus est unde maiores magnam rerum tenetur necessitatibus.",
                            Image = "https://picsum.photos/640/480/?image=339",
                            InStock = false,
                            Name = "Ergonomic Metal Ball",
                            SellPrice = 353.80000000000001,
                            Sku = "makjeqbf"
                        },
                        new
                        {
                            Id = new Guid("068c1cd4-acc6-60ad-ac68-1414282b1157"),
                            BasePrice = 1.4399999999999999,
                            Description = "Cumque aut est voluptatem.\nEum facilis velit fugiat dicta modi voluptatum enim.\nMagni ut ut eveniet.",
                            Image = "https://picsum.photos/640/480/?image=619",
                            InStock = false,
                            Name = "Ergonomic Steel Mouse",
                            SellPrice = 717.72000000000003,
                            Sku = "nppglblrtjq"
                        },
                        new
                        {
                            Id = new Guid("ce0a583b-749e-40f3-389e-65ee0308bd7f"),
                            BasePrice = 706.05999999999995,
                            Description = "Porro quaerat et.\nAutem voluptatem dicta voluptatibus vel neque et sit est animi.\nVitae sapiente et nemo dignissimos hic reprehenderit qui minus.\nQuos consequatur at nihil fugiat consequuntur expedita magnam qui repellat.\nVoluptas id a.",
                            Image = "https://picsum.photos/640/480/?image=756",
                            InStock = true,
                            Name = "Fantastic Plastic Fish",
                            SellPrice = 523.51999999999998,
                            Sku = "egpssfnkuowl"
                        },
                        new
                        {
                            Id = new Guid("91bbe44d-f3e9-d2f3-1f5f-6e1e9827893a"),
                            BasePrice = 157.31,
                            Description = "Tempora blanditiis et eveniet eveniet nobis maxime est facere.\nBlanditiis tenetur deleniti quia quas velit quia quos et.\nNihil qui quisquam voluptas veritatis quia provident cupiditate.\nMaiores error esse architecto molestiae possimus omnis porro quia.\nDignissimos fugiat veritatis molestiae quidem dolor nulla perferendis.\nRerum id et est neque molestiae voluptatem.",
                            Image = "https://picsum.photos/640/480/?image=0",
                            InStock = true,
                            Name = "Handmade Plastic Hat",
                            SellPrice = 503.54000000000002,
                            Sku = "zhqfrdlyd"
                        },
                        new
                        {
                            Id = new Guid("d2e7ee8f-849d-b6e1-3975-bc29b3f762ee"),
                            BasePrice = 730.25999999999999,
                            Description = "Aliquid vel qui nisi ea praesentium qui est.\nQui ipsa ea et.\nId tempora dolores accusamus deserunt consequatur necessitatibus distinctio necessitatibus quia.\nEt quis alias sequi autem omnis quasi reprehenderit a.\nIure facilis a aperiam autem id est sint.",
                            Image = "https://picsum.photos/640/480/?image=84",
                            InStock = false,
                            Name = "Tasty Frozen Chicken",
                            SellPrice = 689.11000000000001,
                            Sku = "osacngtx"
                        },
                        new
                        {
                            Id = new Guid("7af1dd25-6a30-4a0e-9644-62c7d1cdfc4f"),
                            BasePrice = 520.05999999999995,
                            Description = "Omnis voluptatem dicta consequatur dolores.\nDebitis est quisquam quia minus.\nSint dolores repellat labore sunt.\nNesciunt accusantium ut fugit dolorum molestiae occaecati veritatis dolorum sed.\nSint ipsum iste facere labore enim enim eum.",
                            Image = "https://picsum.photos/640/480/?image=448",
                            InStock = true,
                            Name = "Handmade Cotton Soap",
                            SellPrice = 858.52999999999997,
                            Sku = "tsvjlzakeqie"
                        },
                        new
                        {
                            Id = new Guid("93800a91-954d-cea2-0c7c-cb374102feb8"),
                            BasePrice = 649.60000000000002,
                            Description = "In possimus et rerum iure eius illum fugiat labore consectetur.\nDistinctio omnis eum vel molestiae porro eius.\nDolores laudantium reiciendis et sint similique et.\nQuidem id dicta consectetur itaque vero et voluptate.",
                            Image = "https://picsum.photos/640/480/?image=697",
                            InStock = true,
                            Name = "Practical Steel Mouse",
                            SellPrice = 425.73000000000002,
                            Sku = "wdwvlfpx"
                        },
                        new
                        {
                            Id = new Guid("247d22ec-1eec-a49c-3e3a-ad764760fd44"),
                            BasePrice = 796.08000000000004,
                            Description = "Odio fugiat deserunt assumenda numquam.\nIpsam voluptas qui et quia sit eum.\nSoluta nihil laborum saepe.\nAd odit reprehenderit consequatur a accusantium quia assumenda.",
                            Image = "https://picsum.photos/640/480/?image=737",
                            InStock = false,
                            Name = "Rustic Fresh Shirt",
                            SellPrice = 133.28,
                            Sku = "bkedjvvor"
                        },
                        new
                        {
                            Id = new Guid("b4c3ab67-81ea-1196-dc79-e58a2609aea0"),
                            BasePrice = 541.90999999999997,
                            Description = "Repellendus sunt corporis ea et minus pariatur quo voluptatibus.\nNeque aut laboriosam ipsam iure illum unde ipsum ullam.\nDolorem quod quisquam beatae.",
                            Image = "https://picsum.photos/640/480/?image=56",
                            InStock = true,
                            Name = "Sleek Wooden Cheese",
                            SellPrice = 121.81,
                            Sku = "famgwnpx"
                        },
                        new
                        {
                            Id = new Guid("76741f79-f64d-8ee6-4d77-ca6995e1ddd1"),
                            BasePrice = 695.07000000000005,
                            Description = "Voluptatem nulla quia quia.\nUllam quam quasi vitae praesentium cumque cum ut error et.\nLaboriosam vel voluptatum ea illo et.\nEarum recusandae facere omnis corrupti beatae doloremque omnis velit.\nCupiditate ipsum qui occaecati id voluptatem.\nAt omnis non aut non architecto voluptate iste.",
                            Image = "https://picsum.photos/640/480/?image=1020",
                            InStock = true,
                            Name = "Incredible Cotton Chair",
                            SellPrice = 520.85000000000002,
                            Sku = "jtelodkni"
                        },
                        new
                        {
                            Id = new Guid("751072b9-fb2c-8da3-b218-2e1146143f7d"),
                            BasePrice = 907.47000000000003,
                            Description = "Temporibus aut aut nesciunt.\nVoluptatem at voluptatem exercitationem.\nEt ut est est qui consequatur.",
                            Image = "https://picsum.photos/640/480/?image=194",
                            InStock = false,
                            Name = "Small Plastic Ball",
                            SellPrice = 693.83000000000004,
                            Sku = "pqoiqyvzxdpl"
                        },
                        new
                        {
                            Id = new Guid("c6761cbe-5ae5-a908-4f65-8c8f5cdfb5a9"),
                            BasePrice = 238.99000000000001,
                            Description = "Dicta est a sed hic harum saepe.\nQuam rerum iusto temporibus totam sit est minima.\nQui non officiis laboriosam dolor.\nQuam placeat qui laudantium quam.",
                            Image = "https://picsum.photos/640/480/?image=69",
                            InStock = true,
                            Name = "Gorgeous Frozen Fish",
                            SellPrice = 936.22000000000003,
                            Sku = "thkfnxald"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
