// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(WebshopContext))]
    partial class WebshopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Sku")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BasePrice")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SellPrice")
                        .HasColumnType("float");

                    b.HasKey("Sku");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Sku = new Guid("d13c3c9a-6627-8f01-765e-1186deecbbea"),
                            BasePrice = 605.66999999999996,
                            Description = "Voluptas alias nemo quia iusto.\nEt aliquid non.\nLabore sit ut fugit alias.\nFugiat voluptatum quo qui omnis aut consequatur ipsa et.\nAccusamus ratione qui explicabo nisi possimus sit.",
                            Image = "https://picsum.photos/640/480/?image=222",
                            InStock = false,
                            Name = "Generic Rubber Ball",
                            SellPrice = 942.77999999999997
                        },
                        new
                        {
                            Sku = new Guid("ea925e65-9d7e-b56e-e395-e46b7b5bcd32"),
                            BasePrice = 711.02999999999997,
                            Description = "Commodi inventore iusto porro dolores cupiditate dolores quis sed.\nCommodi autem culpa dolor sint et nihil.\nIpsam aut temporibus.\nPerferendis temporibus eius voluptas alias quia est blanditiis.\nQuis soluta iure dolor non dolorem iure qui adipisci.\nFugiat beatae perferendis quia quod.",
                            Image = "https://picsum.photos/640/480/?image=868",
                            InStock = true,
                            Name = "Awesome Frozen Hat",
                            SellPrice = 983.50999999999999
                        },
                        new
                        {
                            Sku = new Guid("1b86fc1b-5f43-3f1c-af2a-cab18f312db2"),
                            BasePrice = 404.80000000000001,
                            Description = "Eos sunt ipsum consequuntur enim nemo dicta aut officia.\nA voluptatibus est tempore laborum id dignissimos magni.\nId dolor quos earum doloremque.\nDeserunt ut et dolores magni.",
                            Image = "https://picsum.photos/640/480/?image=133",
                            InStock = true,
                            Name = "Intelligent Plastic Sausages",
                            SellPrice = 667.19000000000005
                        },
                        new
                        {
                            Sku = new Guid("13c89bf2-f3b9-8f98-7e3b-5ada1cb66cb6"),
                            BasePrice = 900.61000000000001,
                            Description = "Quia sint quia non quas.\nVoluptas ad est qui consectetur minima est commodi.\nQuaerat veritatis libero.\nEum porro quas delectus natus et libero qui.\nAut fugit qui ducimus.",
                            Image = "https://picsum.photos/640/480/?image=682",
                            InStock = true,
                            Name = "Ergonomic Plastic Salad",
                            SellPrice = 363.67000000000002
                        },
                        new
                        {
                            Sku = new Guid("db76bbf0-5096-6dac-006b-caf4c223a607"),
                            BasePrice = 310.10000000000002,
                            Description = "Cum velit perferendis ipsam quas quibusdam sint omnis repellendus.\nDicta temporibus ad facere iste et ea dolorem tempora at.\nDolore mollitia earum iste sed eum aperiam dolorem corrupti.\nExcepturi nemo eaque id nihil omnis voluptas eaque reprehenderit.\nRerum cumque consequatur enim doloremque in nemo reiciendis mollitia.",
                            Image = "https://picsum.photos/640/480/?image=434",
                            InStock = true,
                            Name = "Handcrafted Rubber Chips",
                            SellPrice = 747.40999999999997
                        },
                        new
                        {
                            Sku = new Guid("cfef4e14-0a03-ec2a-b3a7-23247971cae1"),
                            BasePrice = 366.38,
                            Description = "Asperiores aut consequuntur nostrum et magnam.\nVelit debitis voluptatem.",
                            Image = "https://picsum.photos/640/480/?image=550",
                            InStock = false,
                            Name = "Ergonomic Metal Soap",
                            SellPrice = 887.46000000000004
                        },
                        new
                        {
                            Sku = new Guid("5ec1bee0-8dcc-1301-a14f-402e3e816da0"),
                            BasePrice = 957.98000000000002,
                            Description = "Quibusdam voluptas ex et labore nulla voluptatem nulla.\nAccusantium nihil quidem officiis non impedit est fuga.\nAliquam qui rerum quia nihil vitae quis omnis.\nError perferendis perspiciatis ut labore beatae culpa dolorum.",
                            Image = "https://picsum.photos/640/480/?image=235",
                            InStock = false,
                            Name = "Handcrafted Wooden Pants",
                            SellPrice = 228.75999999999999
                        },
                        new
                        {
                            Sku = new Guid("e4201a24-88d2-7dce-1b92-dd002b8c2a6f"),
                            BasePrice = 520.96000000000004,
                            Description = "Eos consequatur eveniet vel nihil est repellat.\nEligendi omnis dicta est et harum et culpa quaerat minus.\nAut cupiditate minima et sint.\nDolor quae doloribus qui veniam eum qui quia laborum.",
                            Image = "https://picsum.photos/640/480/?image=371",
                            InStock = true,
                            Name = "Intelligent Soft Fish",
                            SellPrice = 686.86000000000001
                        },
                        new
                        {
                            Sku = new Guid("aa550e16-cb02-9fca-eaec-585e3d946035"),
                            BasePrice = 434.10000000000002,
                            Description = "Distinctio necessitatibus minima iure qui laudantium explicabo ullam iusto.\nEos magnam magni facere et possimus dicta veniam at.\nVel tenetur est sint quaerat earum.\nEa sapiente ducimus autem.\nEst aperiam totam aut consectetur omnis.\nMagnam qui perspiciatis qui ipsam sapiente tempore ducimus enim.",
                            Image = "https://picsum.photos/640/480/?image=518",
                            InStock = true,
                            Name = "Incredible Steel Chicken",
                            SellPrice = 503.50999999999999
                        },
                        new
                        {
                            Sku = new Guid("cbfe4c44-228d-7a7d-c6d1-eaf5532b6296"),
                            BasePrice = 97.319999999999993,
                            Description = "Iusto vel inventore deleniti.\nRatione quo ea.\nCorporis similique sed modi sint.",
                            Image = "https://picsum.photos/640/480/?image=549",
                            InStock = true,
                            Name = "Licensed Metal Tuna",
                            SellPrice = 546.40999999999997
                        },
                        new
                        {
                            Sku = new Guid("32852f1b-74f1-b7d4-2150-5416b298a236"),
                            BasePrice = 797.33000000000004,
                            Description = "Natus cupiditate error fuga minus qui.\nRatione repudiandae aperiam natus animi vitae incidunt natus inventore.\nNemo quasi ea voluptatem voluptatibus eum.\nAut enim nostrum voluptatem dolor voluptas nisi.\nQuos voluptas et nihil ea numquam dolor enim vel ullam.",
                            Image = "https://picsum.photos/640/480/?image=754",
                            InStock = false,
                            Name = "Generic Granite Computer",
                            SellPrice = 142.80000000000001
                        },
                        new
                        {
                            Sku = new Guid("5f9788a2-6189-01f3-1581-26932b15bce3"),
                            BasePrice = 447.57999999999998,
                            Description = "Aut inventore ad sed.\nQuos qui rerum dignissimos deleniti dolorem cum.\nModi inventore voluptatem eligendi et aut fugit nobis.\nAut iure incidunt voluptas eum ducimus.",
                            Image = "https://picsum.photos/640/480/?image=1026",
                            InStock = true,
                            Name = "Awesome Frozen Shoes",
                            SellPrice = 120.41
                        },
                        new
                        {
                            Sku = new Guid("7033bee6-7fc1-7d34-ed1c-e6ccb6d09da6"),
                            BasePrice = 475.36000000000001,
                            Description = "Minus omnis odio et iure consequatur magni.\nAdipisci nihil tempora quis dolorem accusamus officia cum doloremque et.\nVoluptate perspiciatis qui voluptas ut voluptatem debitis laudantium dolore.\nEa minima incidunt.\nDignissimos ea illum vel et eveniet error dicta aut.",
                            Image = "https://picsum.photos/640/480/?image=381",
                            InStock = true,
                            Name = "Awesome Steel Fish",
                            SellPrice = 205.31
                        },
                        new
                        {
                            Sku = new Guid("142cf0b2-3bfd-30a4-3617-372eafc0605c"),
                            BasePrice = 780.11000000000001,
                            Description = "Cupiditate et inventore corporis ut odio sit.\nEsse laudantium cupiditate ducimus impedit at quisquam repellendus qui.\nSed aut tempore nam sint eligendi asperiores velit architecto rerum.",
                            Image = "https://picsum.photos/640/480/?image=475",
                            InStock = true,
                            Name = "Handcrafted Steel Towels",
                            SellPrice = 762.74000000000001
                        },
                        new
                        {
                            Sku = new Guid("28f3a1a5-a34b-5d50-1e25-5be1255aea9c"),
                            BasePrice = 645.15999999999997,
                            Description = "Sit perspiciatis est et repellendus.\nQuos unde expedita laboriosam.\nEligendi nemo veniam reiciendis aspernatur repudiandae sit nulla.\nSit non sit ullam voluptates quibusdam iste corporis temporibus.\nImpedit et est eaque perferendis dolorum similique sit sit porro.",
                            Image = "https://picsum.photos/640/480/?image=355",
                            InStock = true,
                            Name = "Handmade Granite Ball",
                            SellPrice = 858.47000000000003
                        },
                        new
                        {
                            Sku = new Guid("eefab6dc-3ede-acb7-69df-a191743d7302"),
                            BasePrice = 778.95000000000005,
                            Description = "Iste repellat at.\nQuo ab ex quo eius et occaecati.",
                            Image = "https://picsum.photos/640/480/?image=73",
                            InStock = true,
                            Name = "Refined Frozen Pizza",
                            SellPrice = 634.84000000000003
                        },
                        new
                        {
                            Sku = new Guid("294a204e-ff20-9933-0904-49200ee0f9a7"),
                            BasePrice = 215.25,
                            Description = "Ratione quis placeat qui consequatur saepe occaecati recusandae sed.\nAmet asperiores est dolor temporibus.",
                            Image = "https://picsum.photos/640/480/?image=218",
                            InStock = false,
                            Name = "Gorgeous Wooden Shoes",
                            SellPrice = 116.40000000000001
                        },
                        new
                        {
                            Sku = new Guid("c2bcab25-6e4f-9e1b-9df0-8bd21e4527e4"),
                            BasePrice = 921.55999999999995,
                            Description = "Quis vel excepturi dolorem perspiciatis.\nDolorem sit ut inventore exercitationem et nisi similique rerum.\nOccaecati eos ducimus mollitia.\nIn unde culpa voluptas culpa ut rerum accusamus.",
                            Image = "https://picsum.photos/640/480/?image=571",
                            InStock = true,
                            Name = "Fantastic Wooden Towels",
                            SellPrice = 233.15000000000001
                        },
                        new
                        {
                            Sku = new Guid("3e403cde-6343-e48b-fef4-21a39715f573"),
                            BasePrice = 703.55999999999995,
                            Description = "Rerum corporis voluptas id maiores.\nFacere officiis iure sint quia voluptas in.\nVelit vitae quis et dolorem vitae incidunt doloremque pariatur.\nQui quas et aut cumque dolorem.\nNumquam ad doloremque atque maxime facilis quae aliquam nihil.\nDeserunt repudiandae dolorem.",
                            Image = "https://picsum.photos/640/480/?image=404",
                            InStock = false,
                            Name = "Sleek Cotton Ball",
                            SellPrice = 443.80000000000001
                        },
                        new
                        {
                            Sku = new Guid("09f4c5f9-25b4-5c41-ae02-64d1bcbde2d1"),
                            BasePrice = 723.05999999999995,
                            Description = "Quas dolore error nam.\nDolorem vel dolorem amet ab ab ratione et ratione.",
                            Image = "https://picsum.photos/640/480/?image=424",
                            InStock = true,
                            Name = "Tasty Plastic Cheese",
                            SellPrice = 948.92999999999995
                        },
                        new
                        {
                            Sku = new Guid("2245aa89-4565-cb24-7600-92a4f4f63286"),
                            BasePrice = 652.09000000000003,
                            Description = "Doloremque quaerat non.\nAtque eligendi error voluptatem id modi molestias.",
                            Image = "https://picsum.photos/640/480/?image=909",
                            InStock = false,
                            Name = "Refined Granite Towels",
                            SellPrice = 689.01999999999998
                        },
                        new
                        {
                            Sku = new Guid("51f954f4-de1b-c6cb-2f7c-2e86c9611a5f"),
                            BasePrice = 944.83000000000004,
                            Description = "Voluptas eius ea et voluptas quo dolores ex voluptatem.\nQuasi expedita beatae doloremque odio aut.\nRerum autem velit.\nDebitis aspernatur voluptate eum sequi optio quis.\nQuis omnis aut quis quis dolores.",
                            Image = "https://picsum.photos/640/480/?image=371",
                            InStock = true,
                            Name = "Intelligent Plastic Salad",
                            SellPrice = 766.05999999999995
                        },
                        new
                        {
                            Sku = new Guid("f87566ec-6fdb-8e22-fe5d-d82a008b9c0c"),
                            BasePrice = 800.5,
                            Description = "Pariatur reprehenderit qui ea eum ut consequatur ab.\nDeserunt voluptatum repudiandae in cupiditate consequatur nobis maiores dignissimos sit.\nNobis qui numquam dignissimos accusamus ipsam aut officiis.\nError laudantium sunt recusandae rem aut.",
                            Image = "https://picsum.photos/640/480/?image=339",
                            InStock = false,
                            Name = "Sleek Granite Chair",
                            SellPrice = 334.37
                        },
                        new
                        {
                            Sku = new Guid("db1e9025-99c3-d6de-dc4b-f0d946acffac"),
                            BasePrice = 934.53999999999996,
                            Description = "Ut suscipit omnis voluptatem similique.\nVitae in culpa laborum consectetur praesentium alias aut architecto.\nIn excepturi accusamus quo et voluptatem quia dolorem sunt natus.",
                            Image = "https://picsum.photos/640/480/?image=901",
                            InStock = true,
                            Name = "Intelligent Cotton Car",
                            SellPrice = 926.75999999999999
                        },
                        new
                        {
                            Sku = new Guid("d48f9eb5-1c11-7ead-a99f-2073a997ea5f"),
                            BasePrice = 570.25999999999999,
                            Description = "Voluptatem vel exercitationem libero nulla.\nHic laudantium error qui alias.\nEt est saepe voluptatem libero.",
                            Image = "https://picsum.photos/640/480/?image=57",
                            InStock = true,
                            Name = "Unbranded Fresh Ball",
                            SellPrice = 144.27000000000001
                        },
                        new
                        {
                            Sku = new Guid("e46ace12-4f8e-06b9-89e7-4ee666d30b5d"),
                            BasePrice = 294.37,
                            Description = "Exercitationem voluptatem accusantium eveniet ut ut voluptas eveniet enim dicta.\nDolores odit officia molestiae sint aut dolore alias.\nAut non atque.",
                            Image = "https://picsum.photos/640/480/?image=406",
                            InStock = false,
                            Name = "Unbranded Cotton Shoes",
                            SellPrice = 271.37
                        },
                        new
                        {
                            Sku = new Guid("34267e3f-5dfc-8059-34ec-5de1a45043e4"),
                            BasePrice = 231.97,
                            Description = "Maxime voluptatem nam nobis aut totam quidem.\nId ab eum culpa eligendi iusto.\nConsectetur ipsa quam suscipit aut corrupti quisquam est.\nCorporis voluptatem molestias esse itaque ut.\nQuam at sed maxime laboriosam sint eligendi.",
                            Image = "https://picsum.photos/640/480/?image=450",
                            InStock = false,
                            Name = "Ergonomic Granite Keyboard",
                            SellPrice = 310.01999999999998
                        },
                        new
                        {
                            Sku = new Guid("1f3e73be-4245-f754-4bf9-ec7934d9b103"),
                            BasePrice = 653.54999999999995,
                            Description = "Sit voluptas dignissimos hic consequatur quibusdam.\nAut nam non totam possimus.",
                            Image = "https://picsum.photos/640/480/?image=572",
                            InStock = false,
                            Name = "Gorgeous Soft Bacon",
                            SellPrice = 465.10000000000002
                        },
                        new
                        {
                            Sku = new Guid("704b41a4-e25f-95ba-de76-196614d9f9dd"),
                            BasePrice = 642.20000000000005,
                            Description = "Asperiores nihil sequi.\nBeatae ad blanditiis.\nRepellendus laudantium dolorem.",
                            Image = "https://picsum.photos/640/480/?image=842",
                            InStock = false,
                            Name = "Gorgeous Wooden Table",
                            SellPrice = 853.0
                        },
                        new
                        {
                            Sku = new Guid("4f98e84f-adcd-780f-d817-ee2931c6a9de"),
                            BasePrice = 61.140000000000001,
                            Description = "Laborum enim praesentium dolores omnis ipsa tempore dicta nobis.\nUt dignissimos quos aut.\nUt qui vitae.\nInventore impedit non.",
                            Image = "https://picsum.photos/640/480/?image=997",
                            InStock = false,
                            Name = "Licensed Rubber Tuna",
                            SellPrice = 253.49000000000001
                        },
                        new
                        {
                            Sku = new Guid("a4df0c29-c48b-3051-9a8b-41419608e6a0"),
                            BasePrice = 463.37,
                            Description = "Porro et quis omnis sint sit sint ipsa sapiente aut.\nVoluptatem ad fugit sint quis ut deleniti veritatis qui.\nTemporibus repudiandae tempora ea molestiae reiciendis dolores accusantium aut.\nAliquam sint et amet.\nVoluptas sint expedita quia non illo animi.\nVoluptatem molestiae earum ad unde qui vero.",
                            Image = "https://picsum.photos/640/480/?image=425",
                            InStock = false,
                            Name = "Ergonomic Soft Chair",
                            SellPrice = 952.26999999999998
                        },
                        new
                        {
                            Sku = new Guid("0cc6a683-64ea-67f2-b561-59280e57ea59"),
                            BasePrice = 391.62,
                            Description = "Necessitatibus incidunt inventore dignissimos magni et sed inventore eveniet et.\nVitae voluptate et quas possimus sint ut et aut.\nConsequatur occaecati quaerat.\nImpedit a eos facilis commodi sit.\nRepellendus assumenda similique dolorum.\nNostrum dignissimos omnis eos impedit eum.",
                            Image = "https://picsum.photos/640/480/?image=522",
                            InStock = true,
                            Name = "Refined Fresh Table",
                            SellPrice = 930.39999999999998
                        },
                        new
                        {
                            Sku = new Guid("16e06baa-e8df-c0b1-09a1-cf54fae273f7"),
                            BasePrice = 18.75,
                            Description = "Provident quibusdam nam doloribus odio saepe fugit est exercitationem sunt.\nTempore ipsa officia rerum deleniti libero harum.",
                            Image = "https://picsum.photos/640/480/?image=1020",
                            InStock = false,
                            Name = "Handcrafted Rubber Keyboard",
                            SellPrice = 566.72000000000003
                        },
                        new
                        {
                            Sku = new Guid("e62c061e-3b7f-f987-c9de-baf5a6326652"),
                            BasePrice = 603.64999999999998,
                            Description = "Nostrum provident dignissimos ad aspernatur quibusdam et omnis.\nFugiat eum quis voluptates laboriosam ut perferendis aliquam dolor sed.",
                            Image = "https://picsum.photos/640/480/?image=720",
                            InStock = false,
                            Name = "Refined Plastic Pants",
                            SellPrice = 383.83999999999997
                        },
                        new
                        {
                            Sku = new Guid("7d965809-b883-3664-0ce5-902416e11e0c"),
                            BasePrice = 770.34000000000003,
                            Description = "Autem expedita ut corrupti quo architecto ea fugiat blanditiis eius.\nHarum maxime ad sit officia est.",
                            Image = "https://picsum.photos/640/480/?image=911",
                            InStock = false,
                            Name = "Practical Cotton Shoes",
                            SellPrice = 953.73000000000002
                        },
                        new
                        {
                            Sku = new Guid("13637321-bed7-0945-16c5-07412f244514"),
                            BasePrice = 44.630000000000003,
                            Description = "Culpa in sint aspernatur.\nIste minus vitae sint est quia pariatur ipsam.",
                            Image = "https://picsum.photos/640/480/?image=343",
                            InStock = true,
                            Name = "Ergonomic Frozen Pants",
                            SellPrice = 222.52000000000001
                        },
                        new
                        {
                            Sku = new Guid("c062b278-b94d-9aff-2701-79430883faed"),
                            BasePrice = 835.83000000000004,
                            Description = "Deserunt soluta consectetur occaecati et et.\nAssumenda omnis ut iusto necessitatibus cum sed quo est.",
                            Image = "https://picsum.photos/640/480/?image=741",
                            InStock = true,
                            Name = "Awesome Metal Shoes",
                            SellPrice = 998.96000000000004
                        },
                        new
                        {
                            Sku = new Guid("43118258-a021-1aed-91e8-31069fc8c945"),
                            BasePrice = 512.94000000000005,
                            Description = "Sit rerum voluptates.\nTotam voluptas omnis odio vitae omnis nulla reiciendis et rerum.",
                            Image = "https://picsum.photos/640/480/?image=918",
                            InStock = true,
                            Name = "Ergonomic Cotton Bike",
                            SellPrice = 379.63
                        },
                        new
                        {
                            Sku = new Guid("6b98fe92-de33-3cc1-e6eb-17f9e82e51d0"),
                            BasePrice = 51.75,
                            Description = "Alias veniam dolorem quam eos quia vero repellat excepturi sed.\nEst sed et aut id perferendis aliquam praesentium neque.\nConsequatur nulla eius temporibus doloremque libero.\nEa in et.\nImpedit aspernatur minus culpa est ut sit adipisci alias corporis.",
                            Image = "https://picsum.photos/640/480/?image=661",
                            InStock = true,
                            Name = "Licensed Concrete Table",
                            SellPrice = 645.5
                        },
                        new
                        {
                            Sku = new Guid("fc025a66-f70f-a565-ba44-0a3dc80ed849"),
                            BasePrice = 975.02999999999997,
                            Description = "Error eveniet iusto vel unde ut qui ut.\nAnimi corrupti repudiandae aspernatur et esse consequuntur aut.\nDolor voluptatibus possimus eveniet error dolor maiores similique qui qui.\nRerum vel consequuntur architecto labore animi est.\nAliquid dolor rerum pariatur ab.",
                            Image = "https://picsum.photos/640/480/?image=397",
                            InStock = true,
                            Name = "Handmade Concrete Bacon",
                            SellPrice = 327.29000000000002
                        },
                        new
                        {
                            Sku = new Guid("8e04536b-f2b6-0e09-ef26-d3584adf4b01"),
                            BasePrice = 413.72000000000003,
                            Description = "Aut nihil qui tempore voluptatum placeat non modi.\nMollitia deserunt quo dolorum voluptates suscipit.\nDoloremque modi ratione nobis.",
                            Image = "https://picsum.photos/640/480/?image=994",
                            InStock = true,
                            Name = "Incredible Metal Soap",
                            SellPrice = 500.41000000000003
                        },
                        new
                        {
                            Sku = new Guid("66169898-90da-3fab-4a63-aa77fce905d7"),
                            BasePrice = 591.26999999999998,
                            Description = "Ea ullam qui consequuntur consequuntur quis sapiente fugiat.\nEst dolorem sed a autem.\nDistinctio iure sit veniam voluptas doloremque repellendus dolores ut.\nNesciunt ad autem corrupti.\nProvident eius quia nobis veritatis labore vitae vel laboriosam.\nAsperiores quia voluptas minima veniam blanditiis temporibus nobis.",
                            Image = "https://picsum.photos/640/480/?image=251",
                            InStock = false,
                            Name = "Generic Plastic Pizza",
                            SellPrice = 988.78999999999996
                        },
                        new
                        {
                            Sku = new Guid("f2290d0c-0d9f-91ae-dae6-29656511b2a9"),
                            BasePrice = 283.44999999999999,
                            Description = "Sed accusamus sequi quod ut.\nVoluptatem enim quis et.\nDelectus recusandae qui quia est.\nEaque qui ad.\nVoluptatum sit commodi.\nAsperiores quibusdam maxime ullam omnis.",
                            Image = "https://picsum.photos/640/480/?image=737",
                            InStock = true,
                            Name = "Handcrafted Wooden Soap",
                            SellPrice = 224.31999999999999
                        },
                        new
                        {
                            Sku = new Guid("1848e5c7-7c07-e804-8b15-92f74faf4188"),
                            BasePrice = 116.52,
                            Description = "Placeat aut reprehenderit qui.\nQui explicabo necessitatibus voluptatem quo maiores rerum eum ipsam.",
                            Image = "https://picsum.photos/640/480/?image=147",
                            InStock = false,
                            Name = "Sleek Cotton Shoes",
                            SellPrice = 846.37
                        },
                        new
                        {
                            Sku = new Guid("be4d90d6-56cb-6cb0-8e62-b95f88fab7e8"),
                            BasePrice = 606.63,
                            Description = "Praesentium consequuntur id aspernatur vel aliquid ipsa.\nQuo debitis nesciunt ullam quia totam non omnis voluptatibus perspiciatis.\nId alias inventore nihil rem laudantium ea enim.\nUt eum officia quae optio.\nNam consequatur facilis amet facilis repellendus temporibus distinctio deserunt.\nEt velit hic enim ea minima cum.",
                            Image = "https://picsum.photos/640/480/?image=266",
                            InStock = true,
                            Name = "Rustic Rubber Bacon",
                            SellPrice = 515.63
                        },
                        new
                        {
                            Sku = new Guid("98eb8c7f-6403-f7b8-94a4-e18d9ceab87a"),
                            BasePrice = 895.71000000000004,
                            Description = "Et qui in modi.\nEnim et cumque voluptatibus vitae qui vel eius ratione.",
                            Image = "https://picsum.photos/640/480/?image=565",
                            InStock = false,
                            Name = "Licensed Steel Pizza",
                            SellPrice = 260.01999999999998
                        },
                        new
                        {
                            Sku = new Guid("43b53155-8d05-1747-39fa-cff11aaa854b"),
                            BasePrice = 457.75,
                            Description = "Quia amet qui magni modi enim non doloremque.\nNihil sit vero voluptates reiciendis dicta commodi in.\nQuas ratione non est ut adipisci officiis vel optio.\nEt in sit eos qui omnis.\nNihil dolorem enim cum corrupti.\nNesciunt molestiae et reprehenderit omnis consequatur.",
                            Image = "https://picsum.photos/640/480/?image=98",
                            InStock = true,
                            Name = "Gorgeous Soft Mouse",
                            SellPrice = 718.53999999999996
                        },
                        new
                        {
                            Sku = new Guid("2e8edcb4-5513-14c2-ab3e-a9a1ce2a4cfa"),
                            BasePrice = 777.40999999999997,
                            Description = "Commodi eos repellat sed.\nQui necessitatibus eum et perspiciatis optio ipsum eligendi.",
                            Image = "https://picsum.photos/640/480/?image=224",
                            InStock = false,
                            Name = "Unbranded Fresh Gloves",
                            SellPrice = 36.479999999999997
                        },
                        new
                        {
                            Sku = new Guid("c67412d7-88dd-d364-ec25-b9d7e54578c0"),
                            BasePrice = 70.450000000000003,
                            Description = "Et sit earum.\nNesciunt amet numquam cumque.\nRem modi voluptas molestias voluptates.\nVoluptas earum sit est ut culpa quasi provident modi vitae.\nRem fugit asperiores reprehenderit illum aut dolores iusto.",
                            Image = "https://picsum.photos/640/480/?image=80",
                            InStock = false,
                            Name = "Rustic Metal Chair",
                            SellPrice = 834.79999999999995
                        },
                        new
                        {
                            Sku = new Guid("c0f2a7cf-c474-ca8f-623f-e75e9953d0b8"),
                            BasePrice = 850.98000000000002,
                            Description = "Commodi est ducimus beatae consectetur qui.\nEt ut eum.\nNemo quia et error similique veritatis consectetur.\nOdit repellendus molestiae veritatis et illum.\nMaiores sequi maiores.",
                            Image = "https://picsum.photos/640/480/?image=117",
                            InStock = false,
                            Name = "Handcrafted Cotton Towels",
                            SellPrice = 595.46000000000004
                        },
                        new
                        {
                            Sku = new Guid("040461c6-26b9-0651-afa8-c6c016a40dfb"),
                            BasePrice = 880.30999999999995,
                            Description = "Voluptas veniam quam quia ad rerum quis sit eos.\nQuisquam quo excepturi similique illum.\nEa sapiente labore doloribus soluta adipisci iusto.\nDolores consequatur in amet.",
                            Image = "https://picsum.photos/640/480/?image=1034",
                            InStock = false,
                            Name = "Sleek Plastic Hat",
                            SellPrice = 81.379999999999995
                        },
                        new
                        {
                            Sku = new Guid("8930ab44-9cef-eeee-1dc7-efd4ba827736"),
                            BasePrice = 99.319999999999993,
                            Description = "Delectus et eligendi et laborum necessitatibus est.\nVoluptas placeat est sint explicabo ducimus nam rerum commodi accusamus.\nConsequatur aperiam inventore excepturi consequatur.\nError harum qui laborum harum adipisci eveniet nostrum.",
                            Image = "https://picsum.photos/640/480/?image=545",
                            InStock = true,
                            Name = "Gorgeous Soft Chair",
                            SellPrice = 172.53999999999999
                        },
                        new
                        {
                            Sku = new Guid("3bbbc817-4671-43c8-fd1d-5fc2abd90ea2"),
                            BasePrice = 977.26999999999998,
                            Description = "Assumenda voluptatem velit hic velit quo exercitationem id.\nDolor est id.\nAlias et minus ad.\nEt quibusdam quas minus ipsam quia.\nNostrum ipsa explicabo illo culpa omnis est saepe temporibus.\nQuia soluta ducimus.",
                            Image = "https://picsum.photos/640/480/?image=522",
                            InStock = false,
                            Name = "Fantastic Granite Shoes",
                            SellPrice = 982.0
                        },
                        new
                        {
                            Sku = new Guid("e8af59cd-d201-9aa6-d255-169545d8aaca"),
                            BasePrice = 236.61000000000001,
                            Description = "Sapiente ut neque maiores.\nIncidunt quos in ut.\nOptio eius libero quasi vero et.",
                            Image = "https://picsum.photos/640/480/?image=259",
                            InStock = true,
                            Name = "Incredible Wooden Gloves",
                            SellPrice = 306.31999999999999
                        },
                        new
                        {
                            Sku = new Guid("39db3ff7-fd85-2668-852d-650324e16f63"),
                            BasePrice = 110.34,
                            Description = "Ut consequatur unde.\nSit ea eos possimus illum aliquid eum.\nNumquam nisi omnis.\nVoluptatum dolor quod.\nFugit repellendus pariatur deleniti sed eligendi id.\nId quam qui odit quisquam.",
                            Image = "https://picsum.photos/640/480/?image=330",
                            InStock = true,
                            Name = "Incredible Concrete Hat",
                            SellPrice = 985.77999999999997
                        },
                        new
                        {
                            Sku = new Guid("08543c64-151c-2a07-68ee-8b8f73420c04"),
                            BasePrice = 432.68000000000001,
                            Description = "Suscipit iste iste perspiciatis rerum delectus.\nQuam voluptas laudantium voluptas ut sit.\nNemo officiis et sequi est similique exercitationem occaecati beatae iste.\nQuasi alias ea sunt.\nAssumenda qui vel quam.\nUt earum eos fugiat nihil quo et ipsum unde commodi.",
                            Image = "https://picsum.photos/640/480/?image=955",
                            InStock = false,
                            Name = "Fantastic Soft Shirt",
                            SellPrice = 740.79999999999995
                        },
                        new
                        {
                            Sku = new Guid("a380229a-0cb4-b412-6a13-73e1773647e8"),
                            BasePrice = 610.96000000000004,
                            Description = "Eum id quam ea ratione animi.\nExcepturi aut tempore.\nAnimi ipsum veniam doloribus nihil.\nVitae ipsum vero ipsa.\nArchitecto aut reiciendis inventore ratione nulla sint.",
                            Image = "https://picsum.photos/640/480/?image=369",
                            InStock = false,
                            Name = "Incredible Granite Hat",
                            SellPrice = 827.82000000000005
                        },
                        new
                        {
                            Sku = new Guid("4354a175-0e84-3965-61b0-744317ea8192"),
                            BasePrice = 604.24000000000001,
                            Description = "Quis voluptatem facilis et voluptates vel et dolorum et nostrum.\nVero quia suscipit quidem placeat consectetur quas.\nNon vitae rem aut in tempore dolorem est sint.",
                            Image = "https://picsum.photos/640/480/?image=144",
                            InStock = false,
                            Name = "Awesome Concrete Fish",
                            SellPrice = 790.63999999999999
                        },
                        new
                        {
                            Sku = new Guid("91c68c7a-4bf0-8395-29ae-a9fc205be674"),
                            BasePrice = 411.36000000000001,
                            Description = "Necessitatibus hic reiciendis ducimus eveniet.\nSint et ipsa perferendis ducimus expedita cupiditate delectus.\nSit molestiae non aut ut quasi.",
                            Image = "https://picsum.photos/640/480/?image=1079",
                            InStock = true,
                            Name = "Sleek Concrete Mouse",
                            SellPrice = 278.98000000000002
                        },
                        new
                        {
                            Sku = new Guid("4313d2d8-627c-ad97-f09f-bd4bccfc3987"),
                            BasePrice = 744.51999999999998,
                            Description = "Incidunt voluptatem et veniam aut laboriosam animi voluptatibus.\nNon aut consectetur repellendus dolores debitis et ea est numquam.",
                            Image = "https://picsum.photos/640/480/?image=988",
                            InStock = true,
                            Name = "Incredible Steel Salad",
                            SellPrice = 204.0
                        },
                        new
                        {
                            Sku = new Guid("fed35a9f-ccc6-27f4-a50c-b3f1c8d927bf"),
                            BasePrice = 320.29000000000002,
                            Description = "Laborum quasi eligendi.\nConsequatur deserunt saepe quia ut id expedita delectus.",
                            Image = "https://picsum.photos/640/480/?image=772",
                            InStock = false,
                            Name = "Awesome Metal Tuna",
                            SellPrice = 203.24000000000001
                        },
                        new
                        {
                            Sku = new Guid("62a31edb-b1c1-86bf-3c98-adf8acc4dcae"),
                            BasePrice = 738.05999999999995,
                            Description = "Est rem cum.\nExcepturi qui est enim alias esse minima laborum.\nAut aspernatur molestias cumque et molestias.\nIpsum a eveniet ipsam dolore nobis voluptatibus quia.",
                            Image = "https://picsum.photos/640/480/?image=405",
                            InStock = false,
                            Name = "Small Wooden Chicken",
                            SellPrice = 76.989999999999995
                        },
                        new
                        {
                            Sku = new Guid("ffbafcdc-a852-069a-88bb-34ab6f1007b4"),
                            BasePrice = 901.98000000000002,
                            Description = "Aliquam commodi est omnis velit eum at.\nEt fugiat nihil molestias et.\nUt eos qui cumque ut ut laudantium.",
                            Image = "https://picsum.photos/640/480/?image=427",
                            InStock = false,
                            Name = "Licensed Granite Sausages",
                            SellPrice = 454.13
                        },
                        new
                        {
                            Sku = new Guid("6adbcdf1-5bd2-e56e-bb5e-6949a6084129"),
                            BasePrice = 601.33000000000004,
                            Description = "Aut eos qui error repellat vero repellat dolore.\nQuis unde a voluptas dolorem odio corporis quia.",
                            Image = "https://picsum.photos/640/480/?image=1038",
                            InStock = true,
                            Name = "Handcrafted Metal Bacon",
                            SellPrice = 17.690000000000001
                        },
                        new
                        {
                            Sku = new Guid("cb3c8974-df24-4391-5137-7e1ef3935ff7"),
                            BasePrice = 243.78999999999999,
                            Description = "Et est pariatur amet ut et.\nQuibusdam est ullam assumenda ex harum et beatae.\nQuia ipsa reiciendis aliquid debitis perferendis exercitationem et eos repellendus.",
                            Image = "https://picsum.photos/640/480/?image=909",
                            InStock = false,
                            Name = "Licensed Wooden Computer",
                            SellPrice = 880.75
                        },
                        new
                        {
                            Sku = new Guid("ec04e44a-882f-0eb0-319c-22587bd1bd0d"),
                            BasePrice = 421.63999999999999,
                            Description = "Nulla quia earum quis voluptatem modi incidunt autem.\nUt autem placeat excepturi inventore placeat maiores ipsa sunt enim.\nIste praesentium architecto et sapiente qui et.\nEt qui provident sunt inventore.\nUllam alias voluptatibus et.\nQuos nesciunt deserunt ut debitis velit est eos cupiditate totam.",
                            Image = "https://picsum.photos/640/480/?image=675",
                            InStock = true,
                            Name = "Licensed Granite Table",
                            SellPrice = 857.71000000000004
                        },
                        new
                        {
                            Sku = new Guid("95261b9b-8459-f810-9bc9-5a8860194a21"),
                            BasePrice = 16.32,
                            Description = "Quisquam minus quidem minima eum quaerat ipsa.\nSit aut omnis.\nUt consectetur dolorum non magni quos.\nAut autem et debitis qui.\nVel sapiente qui modi accusamus tempore vel.\nArchitecto aut enim et velit ducimus.",
                            Image = "https://picsum.photos/640/480/?image=333",
                            InStock = true,
                            Name = "Handmade Wooden Pants",
                            SellPrice = 389.54000000000002
                        },
                        new
                        {
                            Sku = new Guid("07cb8c26-3732-d246-8c02-a0ee33354a8e"),
                            BasePrice = 51.729999999999997,
                            Description = "Id nihil voluptatem.\nVoluptatibus eligendi enim itaque tenetur.\nAut nemo in omnis voluptatem labore.\nIste laboriosam excepturi omnis.\nDistinctio omnis autem iste accusantium qui tempore vel.\nMollitia ducimus atque blanditiis omnis ipsum minus esse velit id.",
                            Image = "https://picsum.photos/640/480/?image=197",
                            InStock = false,
                            Name = "Ergonomic Metal Fish",
                            SellPrice = 735.46000000000004
                        },
                        new
                        {
                            Sku = new Guid("b05e4bc7-6544-75b3-96ce-61165ce13eba"),
                            BasePrice = 25.23,
                            Description = "Hic rem nobis doloremque nisi sed eos voluptatibus est.\nReiciendis corporis architecto odio natus iusto asperiores.",
                            Image = "https://picsum.photos/640/480/?image=232",
                            InStock = false,
                            Name = "Rustic Rubber Chicken",
                            SellPrice = 641.10000000000002
                        },
                        new
                        {
                            Sku = new Guid("f932ffa6-e99d-2ed4-a2af-fa40e10010f6"),
                            BasePrice = 404.44,
                            Description = "Eligendi maiores veritatis temporibus sint rerum sit eveniet recusandae reiciendis.\nEt molestias nostrum magni omnis.",
                            Image = "https://picsum.photos/640/480/?image=939",
                            InStock = true,
                            Name = "Sleek Concrete Gloves",
                            SellPrice = 814.0
                        },
                        new
                        {
                            Sku = new Guid("22317c60-be98-badb-deee-564ce0f8ea96"),
                            BasePrice = 462.02999999999997,
                            Description = "Iure ducimus et at.\nSequi repudiandae sed.\nExcepturi veniam ad sunt excepturi nam.\nNobis tenetur ut.\nPariatur ea cupiditate illo consequuntur.",
                            Image = "https://picsum.photos/640/480/?image=522",
                            InStock = false,
                            Name = "Refined Wooden Shirt",
                            SellPrice = 364.52999999999997
                        },
                        new
                        {
                            Sku = new Guid("862f3552-55c8-4338-1a12-5f28b639ebaa"),
                            BasePrice = 325.43000000000001,
                            Description = "Et minus at eius autem laudantium eos facere cumque accusamus.\nSed officiis eum fuga.\nVoluptatem ipsa excepturi non non.\nEum dolorum sed voluptas occaecati et delectus aut iure.\nCum accusamus asperiores quisquam aut omnis corrupti eum et.\nTenetur nobis ea est eum adipisci est dolores adipisci.",
                            Image = "https://picsum.photos/640/480/?image=358",
                            InStock = true,
                            Name = "Handmade Wooden Gloves",
                            SellPrice = 370.58999999999997
                        },
                        new
                        {
                            Sku = new Guid("ffbe5280-9214-b2b3-160d-658ae327aec3"),
                            BasePrice = 741.02999999999997,
                            Description = "Molestiae sequi provident modi reiciendis dignissimos iusto.\nVeritatis incidunt est rem.\nA cum iusto rem architecto voluptatem.\nSint provident ut qui quia ex repudiandae praesentium maxime dignissimos.\nMolestias impedit eius et ut.",
                            Image = "https://picsum.photos/640/480/?image=872",
                            InStock = false,
                            Name = "Intelligent Frozen Pants",
                            SellPrice = 499.24000000000001
                        },
                        new
                        {
                            Sku = new Guid("ee8b88ea-21a2-2f40-aaac-4b7ca7acae4b"),
                            BasePrice = 634.36000000000001,
                            Description = "Nostrum aliquam dolor expedita distinctio voluptas ut eos.\nSit est quis sequi velit quisquam est laborum.\nVoluptates repudiandae est autem nihil voluptatem omnis unde enim libero.\nAut velit a harum numquam accusamus sint odio commodi.\nVoluptas soluta consequatur et vero facere enim eum qui id.",
                            Image = "https://picsum.photos/640/480/?image=399",
                            InStock = false,
                            Name = "Small Wooden Computer",
                            SellPrice = 892.15999999999997
                        },
                        new
                        {
                            Sku = new Guid("85a62dc9-77dd-9020-5ba9-b8e073e66218"),
                            BasePrice = 391.44999999999999,
                            Description = "Ipsum sed distinctio hic.\nEst ad quod maxime qui quas recusandae qui voluptatibus.\nDolorem et quam voluptatem exercitationem qui commodi voluptatibus consectetur laborum.\nIn expedita impedit.\nQui praesentium quae.",
                            Image = "https://picsum.photos/640/480/?image=404",
                            InStock = false,
                            Name = "Small Concrete Bacon",
                            SellPrice = 377.05000000000001
                        },
                        new
                        {
                            Sku = new Guid("fdc9348d-0a16-2cce-8d06-9c5c2766739c"),
                            BasePrice = 999.34000000000003,
                            Description = "Iure mollitia ab aspernatur.\nExercitationem amet ullam totam in vitae autem eos.\nEveniet dolor accusamus.\nEst non ratione.\nVoluptas aut impedit sed maiores aut repudiandae velit beatae incidunt.\nHarum sit eum.",
                            Image = "https://picsum.photos/640/480/?image=198",
                            InStock = true,
                            Name = "Intelligent Cotton Gloves",
                            SellPrice = 805.5
                        },
                        new
                        {
                            Sku = new Guid("eeed3c0c-8485-3a56-7a36-ba89e3dd582f"),
                            BasePrice = 146.03999999999999,
                            Description = "Eum quam eveniet fugiat.\nQuas earum asperiores in cum fugiat a.",
                            Image = "https://picsum.photos/640/480/?image=506",
                            InStock = true,
                            Name = "Practical Cotton Chips",
                            SellPrice = 151.66
                        },
                        new
                        {
                            Sku = new Guid("d83020c1-826a-ad66-4fe8-5040b56af0a9"),
                            BasePrice = 717.84000000000003,
                            Description = "Voluptatum itaque qui est.\nNon sint tempora similique placeat esse illum accusantium amet.\nEsse aliquid aut ut quia.\nEa perferendis voluptate voluptatem numquam aut quam commodi.",
                            Image = "https://picsum.photos/640/480/?image=358",
                            InStock = true,
                            Name = "Awesome Soft Shirt",
                            SellPrice = 313.67000000000002
                        },
                        new
                        {
                            Sku = new Guid("4e613774-f2fc-a7f7-0eb0-832d43b0d6f6"),
                            BasePrice = 324.82999999999998,
                            Description = "Voluptas sit ut ipsam optio corporis iure voluptatem recusandae.\nMinima id veritatis rerum perspiciatis et et exercitationem ut in.\nInventore ut vel vel rerum ipsa.\nAperiam quam voluptatem ut qui porro sint occaecati quae ab.",
                            Image = "https://picsum.photos/640/480/?image=318",
                            InStock = false,
                            Name = "Ergonomic Wooden Gloves",
                            SellPrice = 615.46000000000004
                        },
                        new
                        {
                            Sku = new Guid("1364e7a9-c175-3a10-b71d-31af45bfbe7b"),
                            BasePrice = 714.04999999999995,
                            Description = "Quos maiores repellendus eaque.\nInventore reprehenderit laborum mollitia fugiat rerum alias corporis aut.",
                            Image = "https://picsum.photos/640/480/?image=356",
                            InStock = true,
                            Name = "Generic Steel Sausages",
                            SellPrice = 250.31999999999999
                        },
                        new
                        {
                            Sku = new Guid("7af79ef4-6df8-a962-51c7-1a17370ba7af"),
                            BasePrice = 47.770000000000003,
                            Description = "Quae ipsa provident maxime blanditiis commodi.\nA reiciendis rerum voluptatibus amet exercitationem aut aut voluptatem quasi.\nQuasi explicabo repellendus dolorem quia quidem illo sint voluptas.\nPorro et a est consequatur facilis assumenda.",
                            Image = "https://picsum.photos/640/480/?image=257",
                            InStock = true,
                            Name = "Unbranded Frozen Sausages",
                            SellPrice = 404.74000000000001
                        },
                        new
                        {
                            Sku = new Guid("35831a87-0af1-3671-17e1-28c98fd07926"),
                            BasePrice = 106.69,
                            Description = "Veniam maxime cupiditate dolores cumque autem.\nQuo aut dolores exercitationem non ad.",
                            Image = "https://picsum.photos/640/480/?image=749",
                            InStock = true,
                            Name = "Practical Fresh Hat",
                            SellPrice = 685.72000000000003
                        },
                        new
                        {
                            Sku = new Guid("3a1ba90c-90a1-c767-f45d-b995df6e38f4"),
                            BasePrice = 388.62,
                            Description = "Eum voluptatem accusamus labore facere id.\nSed optio sunt.\nAliquid vitae odit commodi perferendis maiores numquam.\nUt fugit ea consequatur illo cupiditate.\nNam quam dolorem similique aut.",
                            Image = "https://picsum.photos/640/480/?image=337",
                            InStock = false,
                            Name = "Handmade Concrete Towels",
                            SellPrice = 802.08000000000004
                        },
                        new
                        {
                            Sku = new Guid("654b1e3d-0d45-5d80-341d-7ce4f139ee46"),
                            BasePrice = 961.84000000000003,
                            Description = "Et quaerat velit recusandae dolores repellat beatae enim voluptatem et.\nSoluta incidunt doloremque.\nMollitia qui eius qui eum.\nSint vitae possimus eos officiis nulla eos ut.\nNon sint quam provident qui fugiat sequi voluptatibus veritatis in.",
                            Image = "https://picsum.photos/640/480/?image=1015",
                            InStock = false,
                            Name = "Licensed Frozen Fish",
                            SellPrice = 349.70999999999998
                        },
                        new
                        {
                            Sku = new Guid("8f62ea7e-f345-5993-2c8c-8c9f645e401b"),
                            BasePrice = 434.20999999999998,
                            Description = "Illum sunt quia molestiae magni ea eligendi architecto.\nQui eum in id id dolores totam quaerat voluptatem.\nVelit et qui et doloribus velit architecto velit maxime possimus.\nTenetur accusantium quidem minima illum ipsam ut illum.\nAutem id saepe et quibusdam autem.\nCumque dolorum ratione voluptatibus asperiores quos.",
                            Image = "https://picsum.photos/640/480/?image=421",
                            InStock = false,
                            Name = "Fantastic Frozen Table",
                            SellPrice = 237.12
                        },
                        new
                        {
                            Sku = new Guid("10257d95-a332-aaed-c3fb-5e4690a62c56"),
                            BasePrice = 302.14999999999998,
                            Description = "Temporibus facilis vel sed.\nQuae ratione iure veniam.",
                            Image = "https://picsum.photos/640/480/?image=701",
                            InStock = true,
                            Name = "Unbranded Steel Pizza",
                            SellPrice = 123.79000000000001
                        },
                        new
                        {
                            Sku = new Guid("e573d461-0cec-5a16-e5a1-51550939db2f"),
                            BasePrice = 335.32999999999998,
                            Description = "Impedit debitis ad non vel qui praesentium dolorem.\nExcepturi optio est dicta aut.",
                            Image = "https://picsum.photos/640/480/?image=772",
                            InStock = false,
                            Name = "Fantastic Steel Shirt",
                            SellPrice = 640.09000000000003
                        },
                        new
                        {
                            Sku = new Guid("a983e2dc-fbd7-3599-e70a-7a28bcb2f3fb"),
                            BasePrice = 248.28999999999999,
                            Description = "Et reiciendis ut.\nAliquam minus est nam occaecati quis velit non.",
                            Image = "https://picsum.photos/640/480/?image=737",
                            InStock = true,
                            Name = "Gorgeous Metal Pants",
                            SellPrice = 929.10000000000002
                        },
                        new
                        {
                            Sku = new Guid("876dc20b-3764-950c-4c89-d4202ce5c21e"),
                            BasePrice = 365.10000000000002,
                            Description = "Assumenda perferendis ut repellendus perspiciatis voluptas minus.\nVoluptatem molestiae doloremque hic atque ut.\nInventore atque rerum ducimus aspernatur officia.\nSunt quisquam nihil dolore magni accusamus dolores quae ipsam.\nQuia nisi perferendis et quos laudantium maiores eos et.",
                            Image = "https://picsum.photos/640/480/?image=79",
                            InStock = true,
                            Name = "Unbranded Granite Computer",
                            SellPrice = 182.81999999999999
                        },
                        new
                        {
                            Sku = new Guid("643094ec-ef40-a504-583c-b8ec15074bf4"),
                            BasePrice = 781.49000000000001,
                            Description = "Blanditiis est sed.\nQui facilis sit aut et magnam culpa est quaerat rerum.\nModi dolores deleniti et dolorum excepturi.",
                            Image = "https://picsum.photos/640/480/?image=936",
                            InStock = true,
                            Name = "Practical Plastic Car",
                            SellPrice = 869.09000000000003
                        },
                        new
                        {
                            Sku = new Guid("5d9daf9d-8bf5-c8cb-5203-377eadec3a1c"),
                            BasePrice = 797.39999999999998,
                            Description = "Ipsa quod quam ex mollitia et excepturi eligendi dolores sed.\nIure quas unde.\nAut officia minus non occaecati.",
                            Image = "https://picsum.photos/640/480/?image=1057",
                            InStock = false,
                            Name = "Handcrafted Metal Pants",
                            SellPrice = 132.31
                        },
                        new
                        {
                            Sku = new Guid("56ded3dd-835d-5699-01d5-656b9491aba5"),
                            BasePrice = 166.69999999999999,
                            Description = "Inventore et ducimus voluptatum ex et.\nQuae corporis velit neque veritatis nisi.\nQuo tempora laudantium est.\nLaborum voluptatem sit facere ut.\nMolestiae iusto ab suscipit exercitationem velit ut qui.\nVoluptas eum in sed voluptatem sed tempora et quidem accusantium.",
                            Image = "https://picsum.photos/640/480/?image=950",
                            InStock = true,
                            Name = "Practical Fresh Table",
                            SellPrice = 92.760000000000005
                        },
                        new
                        {
                            Sku = new Guid("0d94bade-44ed-03a4-282b-f2a380bfa203"),
                            BasePrice = 504.63,
                            Description = "At quia numquam occaecati temporibus dolores saepe sunt.\nEaque omnis impedit et et quo minima quaerat.\nBlanditiis aut deserunt mollitia rem veritatis numquam eos.",
                            Image = "https://picsum.photos/640/480/?image=1026",
                            InStock = true,
                            Name = "Intelligent Metal Hat",
                            SellPrice = 112.0
                        },
                        new
                        {
                            Sku = new Guid("f276420c-d643-ed43-c707-f098d43f82aa"),
                            BasePrice = 828.39999999999998,
                            Description = "Ex ad in nihil repellat in fuga.\nAliquid ipsam hic quidem dolor.\nEaque incidunt eos at.\nNisi modi vitae.\nEveniet ab explicabo.\nCommodi odit et et qui voluptatum voluptatibus hic quis quaerat.",
                            Image = "https://picsum.photos/640/480/?image=265",
                            InStock = true,
                            Name = "Handcrafted Concrete Mouse",
                            SellPrice = 688.38999999999999
                        },
                        new
                        {
                            Sku = new Guid("91269cb8-d8a8-7c42-5e77-bc7da8ccc3c5"),
                            BasePrice = 885.24000000000001,
                            Description = "Voluptatum blanditiis itaque ut iure.\nCumque sit architecto unde.\nExcepturi tenetur explicabo ut.\nVero enim necessitatibus velit illum ut et et quibusdam.",
                            Image = "https://picsum.photos/640/480/?image=413",
                            InStock = false,
                            Name = "Intelligent Granite Bacon",
                            SellPrice = 472.51999999999998
                        },
                        new
                        {
                            Sku = new Guid("4b4d16c7-1544-b61d-abf0-7c00131b5700"),
                            BasePrice = 957.37,
                            Description = "Nemo libero eos totam voluptas dolores quasi sed neque.\nQuas repellat ipsum sequi qui voluptatibus eum.",
                            Image = "https://picsum.photos/640/480/?image=631",
                            InStock = true,
                            Name = "Small Fresh Sausages",
                            SellPrice = 644.71000000000004
                        },
                        new
                        {
                            Sku = new Guid("ad4960ea-423e-dee5-c43d-38066d5c06f8"),
                            BasePrice = 107.73999999999999,
                            Description = "Ex voluptatem quaerat.\nOptio doloremque explicabo autem sint vitae perferendis sequi architecto exercitationem.\nQuam atque eum mollitia velit eius molestiae maiores voluptatem.",
                            Image = "https://picsum.photos/640/480/?image=575",
                            InStock = true,
                            Name = "Gorgeous Rubber Pizza",
                            SellPrice = 203.03999999999999
                        },
                        new
                        {
                            Sku = new Guid("5dcce244-7b50-94f2-208d-719a4fd21743"),
                            BasePrice = 393.00999999999999,
                            Description = "Consequatur et enim dignissimos possimus ut vel atque magni.\nSunt voluptates quaerat fuga cumque nihil quo non recusandae nihil.\nLaudantium in reiciendis rerum.\nQuam aut rerum eaque expedita reprehenderit.\nDeleniti rerum perferendis qui excepturi.\nAliquid dolores eligendi delectus et aut.",
                            Image = "https://picsum.photos/640/480/?image=356",
                            InStock = false,
                            Name = "Handcrafted Cotton Chips",
                            SellPrice = 367.95999999999998
                        },
                        new
                        {
                            Sku = new Guid("c933ee48-9a06-fd8c-af89-5cae9bb8e70f"),
                            BasePrice = 306.13999999999999,
                            Description = "Nostrum iusto iusto ratione velit animi enim unde ipsam.\nA cupiditate autem neque quia.\nLibero qui ipsum cum sed qui aut quam necessitatibus adipisci.",
                            Image = "https://picsum.photos/640/480/?image=943",
                            InStock = true,
                            Name = "Ergonomic Cotton Shirt",
                            SellPrice = 36.789999999999999
                        },
                        new
                        {
                            Sku = new Guid("c6f354fd-9c82-6077-a2ac-5ce7aa1fcd0b"),
                            BasePrice = 889.16999999999996,
                            Description = "Consequatur quia voluptates eum est et in debitis.\nNecessitatibus ratione rem fuga corporis non.\nDolor animi magnam officia porro officiis maxime.",
                            Image = "https://picsum.photos/640/480/?image=475",
                            InStock = false,
                            Name = "Practical Wooden Towels",
                            SellPrice = 555.91999999999996
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
